/**
 *Submitted for verification at Etherscan.io on 2020-04-30
*/

pragma solidity 0.6.0;
contract Thul_Rithy {
string public inscription =
"|___༻ 5 ༄___|  ++`````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````"
"``````````````````````````````````````````````````````````````````...`..`--`````````````````````````````````````````````````````````````````"
"````````````````````````````````````````````````````.-..```````..:+++/+/:--/-``````..---..``````````````````````````````````````````````````"
"`````````````````````````````````````````````...`--.::---`...-/ss+-+yhs++/++o-``..:y/::+++/.````````````````````````````````````````````````"
"```````````````````````````````````````````.---:-::.:/oyys+/:ss:-/smdsdmdmmyhms..os:----///o-```````````````````````````````````````````````"
"``````````````````````````````````.```````./--sooddhyydmNNNmydsshNNNNNNNNNNNNNNdmdyo++o-:/:o/..`````````````````````````````````````````````"
"`````````````````````````````````.+.`````-/osdNNNNNNmNNNMNNNmhdmmmmNNNNNNNmNNNmdmmmNmdd+/+o++:/:+-.`````````````````````````````````````````"
"```````````````````````````````.-/oydssyhhddhmNNNNMmdmNdhdNMNdmNNmNmNNNNNMNNNNmmNNNNNNMNddhyh/--oy.`````````````````````````````````````````"
"````````````````````````````.-://oyyhdNNNNNNNNNNNNMMNNMNNNNMMNNNNNNNNNMMMMMMMMMMMMNNNmNNNNNNNNdyhmsyo:``````````````````````````````````````"
"````````````````````..`...:ohhhdmmdddNNNNNNNNMNNMMMMNMNNNMMMMNNNNMMNNNMMMMMMMMMMNMNNNNNmNNNMNNmmmNmmmms.````````````````````````````````````"
"```````````````````-..::/yhdmdmmNNNNNNNNNNNNNMNNNNNNNNNNNMNMMNMNNNMMNNMMMMNNNMNNNNNMNNNmmNMMMMNNNNmNmmNd:```````````````````````````````````"
"``````````````````oy:/hhdmddddNNNNNNNNNMMMMMMMMMMMNmNNNNNNNMNMNNNNNNmNNNmNNNNNNNNNNNMMMNmNNMNNNNNNNNNddmy....-``````````````````````````````"
"```````````````` :NdhddNmmmmNmNNMNNMMMMMMMMMMMMMMMMMMMMNNNNNNNNMMNNNNNNNNNNMMMNNNNMMMMMMNNNNNNNNNMNNNmmNy/+-:o-.````````````````````````````"
"``````````````.``oMhhmNNmmNNNNNNMMMMMMMMMNNNNNNMMMMMMMMMMMMMMMNNNNNNNNmNNNMMNMMMMMMMMMMMNNNMNMNNNMMMNmmmmso::oy:.```````````````````````````"
"````````````../oodMNNNNNmmNNNNNMMMMMMMMMMNMMMNNNNNMMMMMMMMMMMMMMMNNNNNMMMMNNNNMMMMMMNNMMMMMMMMMMMMMMMNmmNmhssdo:..``````````````````````````"
"````````````.--smMNMNNNNNMNNMMMMMMMMMNNNNMMMNMMNNMMMMMMNNMMMMMMMMMMMMMMMMNNMNNNMNMMNMMMMMMNNNMMMMMNNNNNmNNNNNNhss:``````````````````````````"
"```````````````-hMNmNNNMMMNMMMMMMMMMNMMMNNNNMMMNMNNNNNmmmmNmmNmNNNMNMNMMMNNNMMMNNMMMMMMMMNNNNMMNMMNNNNMMMNNMNNmdys/.````````````````````````"
"``````````````/mMmNMMNNMMNMMMMMMMMMMMMMMMNNNNNNNdhyssssyhhyhhhhmNmmNNNNMMNMMMMMNNMMMMMMMMMMNNMMNMMNNNNMMMNMNNNmy+:/:.` `````````````````````"
"`````````````-mMhsmMMNNMNMMMMMMMNNNMNNNmdyyyyssoo+/////++++ooosyhhyhddmNNMMMMMMMMMMMMMMMMMMNNMMMMMMNNMNNMMNNNNNdhs/+:../````````````````````"
"`````````````:MNhmNNNMMNNNMNNMMNMNMNdhso++//:::::::::/:///////++syoossyyhdmmmmNNMMMMMMMMMNNMNNNMMMNNMMNNMMMNNNNmmmdhso/.````````````````````"
"`````````````.mMNNNNNNMMMMMMMMMMMNdso///:::--:::-:-:::::::::::::/oosossssyyhhhhdNNNNMMMMMMMMMMNMNNNNMMMMMNNNNNNddddmhs/.````````````````````"
"`````` ```````/MMMMNMMNMMMMMMMMMMdo+/:::---.------------:-----::::://++++oosyyddmNNNMMMMMNNMMMMMNNNNMMMMMNNMNNNddddyyyo:..``````````````````"
"````````````_/hMmMMMMMmNMMMMMMMMmo+//:----....----------------:::::::///++oosydmmNNNMMMMMMNMMMMMNNNMMMMMNNNNNNNNNmdmddo:-.``````````````````"
"`````````````/dNmMMMNNmNMMMMMMMMh+//:--.......---------:-----::::::::////+++oshmmNMMMMMMNMMMMNNNNNNNNMMMMMMNNNNNNNmNNNmy+.``````````````````"
"`````````````:+yNMMNNNmMMMMMMMMMy/:/::-.......--------::---:::::::::::////+++sydmNMMMMMMMMMMMMMNMMNNMMMMMMMNMMNNNNNmNNmNh-``````````````````"
"`````````````::dNNNMMNNMMMMMMMMMy/::::-.-.........----------------::::///////+oshmNMMMMMMMMMNMMMMMMMMMMMMMNNNNNNNNNNNmdNd:``````````````````"
"`````````````.+mNNMNMNMMMMMMMMMMd/::::-.........................-:://///+++///+++shmNMMMMMMMMNMMMMMMMMMNMNNNNNNNNNMMNmmmy-``````````````````"
"`````````....:yyNMNNNNNMMMMNMMMMm+::::--....-.-...........--:/+oosyhyysssso++////++shmNMMMMMMMMMMMMMMMMMMNNNNNNMNNNNNNNmo-.`````````````````"
"`````````.`./hNNNNNNNNNMMMMMMMMMmo:::..................-/oymmNNNmdso+/:::///+/+/+/+ooyhNMMMMMMMMMMMNMMMMMNNNNNMNMNNNNNNNh+-.````````````````"
"`````` `````:dmmNNNNMNMMMMMMMMMMmo::-........-......-/+oyddmdhyo+///:::::::::///+/+++oshNMMMMMMMMMMMMMMMMNNNNNNNNNNNNNmmdo/-.```````````````"
"`````````````ss+NMMNNNMMMMMMMMMMmsssossssoo+//:------:++ooooosssyhyyssso+/:::::::/++++oohMMMNMMNNMMMMMMMNNMNNNNNNNNNNNhdmh+//.``````````````"
"`````````````-:-/hNNdsMMMMMMMMMMmhhdNNNNNNNhs+/::::--://++++ydmNmMm/:yhddyoo//:::://+++oymNMNMMMNMMMMMMMMNMNMMNNNmmNMNdhds:--.``````````````"
"`````````````.-odh/shNMMNMMMNMMMo:+//:/++soooo+/:-----://ooohmodNNd/-/++++//:::::::://++yyNMMMMMMMMNMMMMMMMMMNNNNNNNNNNNNd/-..``````````````"
"``````````````-ys:/ooohNNNMMMMMN/::/ydNNMNyoyys+::-.--:://+/dh+/oo/:::/::----:::::::://+osdMMNMMMNMNMMMMMMMMMMNNNNNNNNNNNNd+..``````````````"
"``````````````-ooo/--::ymNMMMNMN::oNMymNMN/`:oo+::---:///++//://///+//:----------::::/+/osdMMNNMMMMMMMMMMMMMMNNNNNNNNNmNmddy-.``````````````"
"````````````````..```.:/+dNNMMMm:/yyo+oyhy//+s/:::-.-://+//////::::-:-------------:://++oohNMNNmMMMMMMMMMMMNNNNNNMNNNNNNNhhy+:..````````````"
"``````````````````.```::ydNNNNMh-:::::-://++o/::::...-::///:----:--------.--...----:::/+osdNMNmdmNMMMNMMMMNNNNNNNNNNmNNmdyys/:--.```````````"
"``````````````````.-.--hmNMMMMM+.-----::::::::::--..----::::--..------..........---::::/oymMMNmdmNmdNMMNmNMMMMMMNNNNNNNNmddhosso:.``````````"
"``````````````````./shyoosNMMMN:...------:--.-:---..---:--:::----.....-:.......--:-:::/+oymMMNmhhmdmmNMmdmNMMMMMMMMMMNNNNNNmdyyso-``````````"
"```````````````````.:so+ydNNNMh....-----.--:---.....---::::///:----...........--::::///++sdMMMNmNNNNNNmhyhNMMMMMMMMMMMNNNNNmhmdyo-``````````"
"````````````````````.:+shdmmmM/`...--..-.-----......-----.--://::----.......----://////++shNMNmNmdhsyhoodNMMMMMMMMMMNNdNNNdhooo++..`````````"
"``````````````````````.///+ymN.`........-::-..--.--:::------/++/::/::-------:::////////++oshhyhysy+o/+hNMMMNMMMMMMMMMNmhys//+oo:..``````````"
"```````````````````````.:+symN-....`...-::--/+s+://+oyhhhyoooo/::://///:::::::///://////++ssssss//:+yNMMMMMMMMMMMMMMMNhyysyoos:.````````````"
"````````````````````````+dddmds.......-:::::+sso++ooyssso++++///::://::://////////://////++ossyNhdmNMMMMMMMMMMMMMMMNmNNNmNmhy/.`````````````"
"`````````````````````````./+o+do..----:+/::://osososyyssysoo+o/o+ossooo/::////////:///////+ooyhhmNMMMMMMMMMMMMMMMMNNNNNNNmo-...`````````````"
"```````````````````````````.-/sNs--:::///:://osoosss++/os+++++/sssshyhhso///+++///:////////+shddmNMMMNNNNMMMMMMMMNNNNmmNho/.````````````````"
"````````````````````````````..:dy/::::://oo+/+:::///+++++o+ooooooyoshdmho/////////:////////+ohdmNMMMMNNNMMMMMMMMMMNNNmdys-.`````````````````"
"```````` ````````````````````..y::/::::+ohs//+osysssoy+:o+:o/:/o:o/:hhyy+/://+++///////////+shmmNMMMMMNNMMMMMMNNMMMNNNNyo:``````````````````"
"```````````````````````````````:+::::::/osyohmh/:--.`..`.:-///+y+hho++/////+//++///////////+shmmNMMMMMMMMMMMMMNNNMNNNMNyy:``````````````````"
"``````````````````````````````...-:-::::/+sydNd+/++:-:/:-:::+ooos+o/:::://+//++///+///////+oshmmMMMMMMMMMMMMMMMNNmmmdhy/-.``````````````````"
"``````````````````````````````.`````.:::://::+syso+::::::///+++++///::://////+//////+/+++++oydmmMMMMMMMMMMMNNMMNmyhhs:-.````````````````````"
"```````````````````````````````````.`.::/::-::////:::/:////+++/+//::::://///++//////++++ooosyhymMMMMMMMMMMMMNNNNNddh/..`````````````````````"
"``````````````````````````````````````.:/::-::-:/+//+++oosyso/:::::::::::://///+/+++oooossssyysyNMMMMMMMMMNNNNNNNNNs-```````````````````````"
"```````````````````````````````````````.:/:::---:/+osyyyys+::-::::-::::::////////++oosooooososoymMMMMMMMMMMNNNMMMNs:.```````````````````````"
"`````````````````````````````````````````:+/:-------::::::--------:::::://+++++oooossoooo++++oosdMNNMNNNNNMMNNmmmh+/.```````````````````````"
"``````````````````````````````````````````-/:--::-.-----:::::::::::-::/++++ooosssssssoo+++++++osdMNNNNNNNNNNNmysoo+-````````````````````````"
"````````````````````````````````````````````:/:-----:////++++o+/::::/++++osssssyyssoo+++++//++oohMMNNNNNNNNNdsso+:.`````````````````````````"
"`````````````````````````````````````````````.-:---:+ooooooossoo++o+ooossssyyysssooo++++////+/++ymNMNNNNNmmy/-.``.``````````````````````````"
"    ````````````````````````` ````````````````.:+/:oosyysyyyyyyyyyyyyyyyyyyhhysyoooo+//////////++sdNNNNNmhs:-.```.``````````````````````````"
"``````````````````   ``````````````````````````-+ossyhhhhhddddddhhhhhhyhhhhyyyysso++/////////////++shdddy/-....`````````````````````````````"
"``````` ```````````````````````````````````` `./+osyosdmmmmdddddddddhyssoooooo+++//////////////////+:--:-.``````````````````````````````````"
"````       ````````   `````````````````````` `.:/:-:.`..:+oyhhhysoo+++++++++/////////////////////////:.`````````````````````````````````````"
"`````    ``  ````  `````````````` ```````````````..-.--....`--:::::-/////++////////////:/://///////:/:/:.```````````````````````````````````"
"````````````````````````````  ```````````` ``.....-.-.----.-...---::////////////::::::::/:::///////:::://-.`````````````````````````````````"
"` ` `````````````````` ```````````````` `  --.``.--::::-:/:-:::.-///////:///////:::::::::::::/::::::::://:/:.``..```````````````````````````"
"````````````` `` ```````` ``` `````````````+```.::/::///:+/::-++:+o++//::///////:::::::::::::::::::::::::::::-.hdo-`````````````````````````"
"``` ``````````````` ```````````````````````.`./::--::+:++oo/::-+oo+++/:/://///:::::::::::::::::::::::::::::--/hdyhyo/-/-````````````````````"
"``` `````````  ``              ````````  ` `-.``-----```:oyoo+/:yo//:::::::://::::::::::::::::::::::::::::-:yddhyhdddmhh+-.`````````````````"
"   `          ``               `   ``````` `-:yhs:.smhdy+-.+so/:y/::::::::::::::::::::::::::::::::::::::::ohhhhhddhhhdhdyys+-.``````````````"
"             `  `                   ````  .//yhs+.:dd+ooydo/ss+++:::::::::::/:-:::::::::::::::::::::::::+hdmhhyhhhhhhhhhyyyyyo+:.```````````"
"    `        `       ``     `` ```` ````-odyhdyy:.hmyyNNd+oyy/::--:::::--::::::-:-:://///:::::::::::--/hmddhyyhhhhhhhh  PIERRE MARIE RIVIERE"
;
}