/**
 *Submitted for verification at Etherscan.io on 2021-03-07
*/

/**
 *Submitted for verification at Etherscan.io on 2021-02-13
*/

/**
 *Submitted for verification at Etherscan.io on 2020-12-05
*/

/**
 *Submitted for verification at Etherscan.io on 2020-11-27
*/
//BBQBBBBBBBBBQBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBQBBBBBBBQBQBBBBBBBBBQBBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBQBBBBBBBBBBBBBQBBBQBBBBBQ
//QBBBQBBBQBBBBBBBBBBBBBBBBBBBQBBBQBQBQBBBBBBBBBBBBBQBBBBBBBBBQBQBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBQBBB
//BBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBQBBBBBQBQBQBBBBBBBBBQBBBBBBBBBQBBBBBQBBBBBBBBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBQBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBBBBQBBBBBBBBBQBBBBBQBBBBBBBBBBBBBBBQBBBBBBB
//BBBBBBBBBBBQBBBBBBBBBBBQBBBQBBBBBBBBBBBBBQBQBBBQBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBBBQBBBBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBB
//QBBBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBQBQBQBBBBBBBBBBBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBQBBBBBBBQBQBBBQBBBBBBBBBQBBBBBBQisQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBB
//BBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBi  uBBBBBBBBBQBBBBBBBQBQBBBBBBBBBBBBBBBB
//QBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBQBBBBBBBBBBBBBBBu  . BQBQBQBBBQBBBBBBBBBBBQBBBQBBBBBBBBBBB
//BBBBBBBQBQBBBQBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBQBi .: :BBQBBBBBQBBBBBBBBBBBBBBBBBQBQBBBBBQBQ
//QBBBBBBBBBBBBBBBQBQBBBQBBBBBBBQBBBBBBBBBBBQBBBBBBBBBQBBBQBBBQBBBBBBBBBBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBQBQBBBBBBBQBBBBBBBQBBB: .:. 7BBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBQBBBBB
//BBBQBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBBBBBBBBBQBBBBBBBBBBBBBQBBBBB: .::: IQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
//QBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBQBBBBBBBQBBBQBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBBQBBBBBBBQBBBBBBBBBBBQBQBBBBBQB7 .:::: SBBBBBBBBBBBQBBBBBBBBBBBBBBBQBBBBBBBBB
//BBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBBBBg .::::: 5BBBBBBBBBBBBBBQBBBBBBBBBQBBBQBBBBBBBB
//QBBBQBBBBBBBBBBBQBBBBBBBQBBBBBQBBBBBBBBBBBQBBBBBQBBBBBQBBBBBQBBBQBBBBBBBBBBBBBQBBBQQggdbKPXXIS5XSqXPPEZRRBBBBBBBBBBBBBBBB: :::::: 7BBBQBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBQB
//BBBBBQBBBBBBBBBBBBBBBBBQBQBBBBBQBBBQBBBBBBBBBBBBBBBBBQBQBBBQBBBQBBBBBBBQBBBQRdPS51Uu21I2I252SI52IUI2IU2u2UI5PdQQBBBBBQBBB .::::::..QBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBB
//QBBBBBBBBBBBQBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBBBBBBBQBQBQBQgPXUUu2UI5XISSKSKXXXX5KSX5KSXSXSXSS2522u22bgBBBBBK .::::::: 5BBBBBBQBBBBBBBBBQBBBBBBBBBBBBBQBBBQB
//BQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBBBQBBBBBBBBBBBBBBBBBBQbKUUu22S5XSXSXSKSKSKSKXKXKSKXKXqSqXKXqSKXK5XI5UU1SEBBd :::::::. :BBBBBBBQBBBBBBBQBBBBBBBBBQBBBBBBBBBB
//BBBBQBBBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBBBBBMd52uI2S5K5KXKSKXqSKSKXqSKXqSKSKKPqEdDdZPPKqXKSKXKXKSSUUUg1 .::::::: iBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBB
//BBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBBBBBBBQBEKU2155K5XSKSKXqSKXKXqSKSKSKSKSqSPPggZKX25SdZMEbKqXKXKSqSKSXP2 :::::::. PBQBQBBBBBBBBBBBBBBBQBBBBBBBBBBBQBBBB
//QBBBBBBBBBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBBBBBBQBBBBBBBBQbS1UUX5XSKXqXqSKSKSqXqSKSKSKXKSKXKKbgZjr.......:r5ZDqqXKSKXqSKXPP. .::::. LBBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBQBQBBB
//BBBQBBBBBBBBBBBBBQBQBBBQBBBBBBBBBBBQBBBQBBBQBQBBBQBBQq512IS5KSXXKXKSKSqSKSqXqSKSKXKSKSKSqXEDJ...:::.:.:...:IgPqXqXqXqXqKEj. .....PBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBQBB
//QBBBQBBBBBBBQBBBBBBBQBQBQBBBQBBBBBBBQBBBQBBBBBBBBBPIuIISSKSKSqSqXKSKSXXK5KSKXqXqSqXKSKSqXbZi..::::::::::::..YgKqXqXqXqXSKBBqr:rrSBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBBBBBBBQBBBBBBBBBBBQBBBBBBBQBBBBBBBBBRKj2IXSKXKSKSqSXSXIS2SISISIX5qXKSKSKXKXqXPgr.:::::::::::::::..1DKKXKSKSKIgRBBqv175XqBBBBBBBBQBBBBBQBBBQBBBBBBBBBQBBBBBQBB
//BBBBBBBBBBBBQBBBQBBBBBBBQBBBBBQBQBQBBBBBBBQBBQ512SSXXKXqXKSKSK5SSPPEdEddPPS5IXSKSKSqSqXqPq..::::::::::::::::.:ZPSKSKXKIbRRQQr7v7UP2UgBBBBBBBBBQBBBBBBBQBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBQBBBBBBBBBBBBBQBBBQBBBBBBBQBQBBBQKu55XSqSKXKXKSKXX5KbDZgEDEDZgZgbq2XSKSKSqXKXDu.:::::::::::::::::..dPKSKSK5XRRgBqr7Lr5PX2UgBQBBBBBBBQBBBBBBBBBBBBBQBBBBBBBBBB
//QBBBBBBBBBBBBBBBQBQBBBQBBBBBBBQBQBBBBBBBBBqUUXSXXKSKSKXKXKXKIPZDEZEZEZdZdDEgZb5XSKSKSqSqdS.:::::::::::::::::..EPXKXqSXgQRQQJrLv7IbSXI1QBBBQBBBQBBBBBBBBBBBBBBBBBQBBBBBBB
//BBBBBBBBBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBQDU25KSKXKXKXKXqSKSKIPDDdDdEEZdZdZbZdZDEIKSKSKSKSPZ:.:::::::::::::::..7gKKSKSK5ZEZMRr7vLrXPKSXUPQBBBBBQBBBBBBBBBBBBBBBBBBBQBBBBBB
//QBQBBBQBBBBBBBQBBBBBBBBBBBBBBBBBBBBBQBQXu5SKSKSqSKSKXqXKXX5KZDdEbEdEEEbZdZdZdZgPIqXKSKSKXEq..:::::::::::::..igPqXqSPqdKqXZjir7ri5dXq552BBBBBBBBBBBBBQBBBBBBBBBBBQBQBBBQB
//BBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBBBBBbUUX5KSKXqXqXKSKXqXKSSqgdZdEdEbZdZdZdZdZEgbSSKSqXKSKKDPi...:::::::::..7gbqSqSqqJXEPZgYr777iKPqSKIIBBQBBBQBBBBBBBBBBBBBBBBBBBBBBBQBB
//QBBBBBBBBBBBBBBBBBBBBBQBQBBBBBQBQBBBIUIXXqXKSKXqXKXKSKSKXKIbZZdZdEbZEZdEEZbZdDZZIKXKXKSqSqKEg5i..........7qMPqSKXqqKr7vsJj:iiri:PbXK52KBBBBBQBBBBBBBBBBBBBBBBBBBQBBBBBBB
//BBBBBBBBBBBBBBBBBQBQBQBBBBBBBQBQBBguI5XSqXKXKXqSKSKSKSKSqSSXgdDdZbZdZbZdZdZdZEgPSXqXqXqSqXqKPZgPSsvr7vuXZgEKqSKXKXEuvsusU7:iii:7DqKSSjQQBBBBBBBQBBBBBBBBBBBQBQBBBBBBBQBB
//BBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBPu5SKXqXKXKSKSKXKSKSKSqSqSSPMEZdZdZdZbZdEdZdgES5KXqXqXqSqXKXqqbdgDgDgDZPPXqSKXqXPdr:77Lsi:iii.SEqSS1qBBBBBBBBBBBBBBBBBBBBQBBBBBQBBBBBBB
//BBBBBQBBBBBBBQBBBBBQBBBQBBBBBBBBX1S5KSqXKXqXKKKXqSqXKSKXqXK5SbgEZdZEZdEdZEDEgdX5KXqSKXqSqXKXKSqSqKqKqXqXqSKXKSKXqqdiiiiii...:..DPSXUIBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQ21XSKXqXqKPqPqPqPKqSqXqXKSqSKS5KZZgZZEZEDEgZDqS5KXqXKSKSqXqSKXKXKXKSqXKXKXKXqXKXKXZI:irr7i.::..vgKX2IBBBBBBQBBBBBBBBBBBBBBBBBBBQBBBBBBBBB
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBQUUXSKXqKbPPXX5X5KPPPPXKSKXqXqSKSSIqqdEZZDEZPq555KXKSKSqXKSKXKSqXKSKSKSKXqSKSqSKXKXqEs:rrr7:.::..EbKUIBBQBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBB
//QBQBQBBBBBBBBBBBQBBBBBBBBBBBRUIXSqXPPP2s7v77777vYIqbKqXKXKXKSXSKSXISSX5XIS5XXXSqXqSKXKSKSKSKSKSKXKSKSKXqXKSKXqXqqZrirrr7.:::.igq15BBBBQBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBQBBBBBBBQBBBBBBBQUIXSKXPPS777v7LvYvLvvrv1bqKSKSKSKXqSXSK5XSX5KSKSKSKXqXKXKXqSKXKSKXKXqSKSqSKSqXKXqXKXbqiirr7i.::..1Z1KBBBBBBBBBBBBBBQBBBQBBBQBBBBBBBBBBBBBBBB
//BBQBBBBBBBBBBBBBQBBBBBBBQBQ2IKSqSPPUrvvLvYvLvYvYvv77JbKKXKSKXqSKXKXKSqXKXqSKXqXKXqXKXKSKXKSqSKSqXKXKXKXKSKSKXKXqb2:rrrr:.::..ZIdBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBBBBBBBQBBBBBQBBI2XSKXKPIrLvYvYvYLYvYvYvY7rJPXKXKXKSKXKXKSqXKXqXKXKSKSKSKSKSqXqXqSqSKSKXqSKSKSKXqXKSKKD7:irrr.::: rPQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQ
//QBBBBBBBBBQBBBBBBBBBBBBBBK1XXKSqXPv7vLLYvYLYvYvYvYvY77KPXqXKSKXqSKXKSKSKSKXKSKSKXqXqXqSqSKSKSqSKXKSqSqSKXKSKSqXPbrirr7i:::. SBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
//BBBBBQBBBBBBBQBQBBBQBBBBZ1XXqXqXPX7vLvLvsvLvYvYLYvLvLrKqKSKSKSKXKXqXKXKSKXKXKSKSKSqXKSqSqXqSqXKXKSKXKSKXqXKXKXqbK:rir7:.:. :BQBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBB
//BBQBBBBBBBBBBBBBBBBBQBBB15SKXKXKqP7vvYLsvYLLLsvsvYvYv7XPXKSKSKXKXKSKXqXKSKSKXqXKXKSqSKXKXKXqXqXKXqSqXqSqXKSKSKKDs:irrr.::. ZBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBB
//BQBBBBBBBBBBBBBBBBBQBBBSISKSKSqSKq1rvvYvYvsvYvsvYvLv7YbKKSKSqXKXKSKSqXqXqXKXKSKSKXKXKSqXKXKXKSKXKXKSKXqXqSqSKXPEr:rr7i.::..BBBBBBBBQBBBQBBBQBBBBBBBBBQBQBQBBBBBBBBBBBQBQ
//BBBBBBBBBBBBBBBBBBBBBBQ15XXKXKXqXqPJrvvYvYLYvYLYvYv7vPqqXKXKSqXqSKSKXKXqXKSKSqSqSKXKXKXKXqSKXqXqXKSKSKXKSKSKSKPb:ir77:.:: 7BBBQBBBQBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBQBBBBB
//BBBBBQBBBQBBBQBQBBBQBQK2XSKSqXqSKXPPU777LvLvYvLvv77sPqPXqSKXKXKXKXKXKXKSKSKSKSKSKXKSqXqSqXKXKXKXqSKSqXKSqSKSKXEU:irrr.::. BBBBBBBBBBBBBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBB
//BBBBBBBBBBQBBBBBBBBBBBuSXKXKSKSqSqXPPPuL7777r7r7vuSdqPXqSKSKXqSqXKXKXqXKXqXKSqXKSqSKSqXqSqSKSKXqSqXqSKSKSKSqSqEL:rr7i.::.:BBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBQBBBQBBB
//BBBBBBBBBQBBBBBQBBBBBdU5KXKXKSKSKXqXqKPPPI21U1SSbPPKKSKSKSqXKXKSKSKSKSKXKSqSKXKSKSqSKXqSKXqXqXqXqSqSKSKSqXKSqqZiirr7:.:. 7ZqgQBBBBBBBBBBBQBBBQBBBBBBBBBBBBBBBBBBBBBBBBBB
//QBBBBBBBBBBBBBBBBBBBQXUKXKSKSKXKSqXKXqXPKPPbPbqPqKXqSKXKSKSKXKXqSqXqSqSqXKXKXKXKSqXKSqSKXqXqSKSKXKXKSKXKXqSKXdK:irrr.::..EPS121SSPbggRRQQBBBBBQBBBBBBBBBBBBBQBQBBBBBBBBB
//BBBBBQBQBBBBBQBBBBBQB1SSqSKSqSqSKSKSqXqXqXqXKXKSqXKSKSqSqXqXqSKXqXKSKSKXKXKSqXKXKXKXKSKSqSKSqSqSKXqSKXKSqXXSKqj:rr7i:::.igPSK5S25UIUUu2u215PBBBQBBBBBBBBBQBBBQBBBBBBBBBB
//QBBBBBBBQBBBBBBBBBBBQU5XXqXKSKXKXqXPqPqbqPKPSKXqXqXKXKXKSKXKXKSKXqXqSKXKXqSKXKXqSKXKXKSKSKXqXKXKXKXqXKSXSX22SQ7:rr7:.:. 2gKKSKXXSX5XSX5X5522uQBBBBBBBBQBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBQBBBBBBBBQuXSqXqSKSqXPPZDgDgDgggEdqqSKSKSqXKXqSKXKXKXKXKXKXKSKXqXKSKSqSKXKSKSqXKSKSKXqXKXKSqXX1XgBBi:rrr.::..gPqSKSqXqSKXKXKXKSX5UKBBBBBQBBBBBBBQBBBBBBBBBBBB
//QBBBBBQBQBBBBBQBBBBBMU5XSKXKXqXdZgSYi::::i7IdgbPXKSqSqSKSKSKXqSKSKXKSKSKXKXKXqXqXKXqXqXqXqXqSKXKSqXqSqXXUbBBBB.ir7i::: LEKXqSKXqSKSKXKXKXqSXuPBBQBBBBBQBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBBBBBBBBBBQ1SSKXKXqKDDs:. ....... .rEZPKKXKSKXKSqXKSKSKSKSKSqSKSqXqSKSqSKXqSqXKSKSKXKXKSqSKSK2KBBQBI.ir7:.:. QB2XSKXKXKSqXqSKXKSqXJMBBBBBBBBBBBBBBBQBBBBBQBBBQ
//QBBBQBBBBBBBQBQBBBBBBU5KXKSqKDP: ..:::::::::...IDPXKSKXKXqXKSKXqXqXKSqXqSKSKSKXqXqXqSqXKSqSKXKXqXKXqSq5IRBBBBr:rrr.:: :BB5IXXqXqSKXKSKXKXKXU1BBBBBBBBBBBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBQBBBBBBBBBUSXKXKKEb..:::::::::::::.. IZPXqSKSKSKXqSqXKSKSKXKSKXqSKSKSqSKXKSKXKSqXKSKXKSKXKSX1BQBBB.ir7i::. ZBB2SSKSqXqSKXKSKSqXI7BBBBBBBBBBBBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBBQBBBBBQBBq1XSqSPZr ::::::::::::::::..ZPqXKSKXqSKXKSKXKSKSKXKXKXKXKXqXqSKSKSqSKXKXKXqSqXKXKSIEBBBD.ir7:.:..BBQISKXKXqXKXKSqXKKXrgBBQBBBBBBBBBBBBBBBBBBBBBBBQB
//BBBQBBBBBBBBBBBBBBBBBgU5KSqPE..::::::::::::::::. UZXKSKXqSKSKXKSqXKSKSKSKSKXqSKXqSqSqXqSqXKXqXKXqSKXKXK52QBBJ.rrr.:. vBBXIKSqSKSKXKXKXKqXrPQBBBBBBBBBBBQBBBBBBBBBBBQBBBB
//QBBBBBBBBBBBQBBBBBBBQB1SXKXdb..::::::::::::::::: 2dqSKXKSKSqSKXqSKSKXKXKXKSKXqSKSqSqSKXKXKXKXKSKXKXKXKSX2IRB:::r:... BBXUXSKXqSqSKXKXKqSrSBBBBBBBBBBBBBBQBBBBBBBBBBBBBBB
//BBBQBBBQBBBBBBBBBBBBBBE1XXKqgi.::::::::::::::::..ddKqXqXqSKSKSqSKSqSKXqSKXKXKSqXqSKSKSKXKSKSKSqSqSqSKXKSX5SKviii. ..rgXIKSKXqXKSKXKSqP2i5BBBBBBBBBBQBBBQBBBBBBBQBBBBBBBQ
//BBBBBBBBBBBBBBQBQBBBBBBUIKXqbP...:::::::::::::. JgKKSqSKSKSqSKXKXKSKXKXKSKXKXKSKSKXKXKXKSKSKSqXKSKXKXKSKXXSqPEPbXPbDEPXKSKSKXKSqSqXPqurKBBQBQBBBBBBBQBBBQBBBBBQBBBBBBBBB
//BBBQBQBBBBBBBQBBBBBBBQBD25KXPZK...::::::::::. .sMPqSKXKKKXKKKXKSKSKSKSKSqXqSqXqXKXKSqKqXKXqSqSqSKXKSKSKSKSKXqKPPEPdPqXqSKSKSKXqXKXPXvrEBBBBBBBBBBBBBBQBQBBBQBBBQBBBBBBBB
//QBBBBBBBBBBBQBBBQBBBBBBBSISKXPZDr. ..........rKgqqXKXqqEdZEDEdPPXKXKXqSqXKSKSKXqSqKPqbPdPPPPXKXqXKXqXqXKSKXqXqXKSqKKXKSKXKXqSKXqXPU77QBBBBBBBBBBQBBBBBBBBBBBBBBBBBQBBBBB
//BBBBBBBBBBBBBBBBBBBQBBBBBU5SKXqbgdUr:...::rYbgDqqXqKZDZqX121SqZDZqqXKSqXKSKSKXKKPPbS5u1j115XbPqXqSKSKSKSqXKSKSKSKSKSKSKSKXqXqXqqKLruBBBBBQBBBBBQBBBBBBBQBBBBBQBBBBBBBBBQ
//QBBBBBBBBBQBQBBBBBBBQBQBBQj5SKXqqdEMDgEZEgDgPPXKXqdgXv::...:.::7IgEPXqSKSqSKSKKbXUvvr77v7777LIPPXKSqSKSqSqSKSqSKXKSKXKSKSKXKKPq2r7dBBBBBBBBBBBBBBBBBBBQBBBQBBBBBBBBBBBQB
//BBBBBBBQBBBQBBBBBBBBBQBBBBRj5SKXKKqqPqPPdPPKKSqXqdEr:.::iii:i::..iqZPSqSKXKSqqd177vvYvsvYvYvvrYXbKKSKXKXqSKSqXKXKSKSKSKXKXqXPIvrIBBBBQBBBBBBBQBBBBBBBBBBBBBBBBBBBBBQBQBB
//QBBBBBQBBBBBBBBBBBBBBBBBQBBRuSSKXqSKXKXKXKXKSKXPEP:.:i:iiiiiiiii::.2ZqXKXKXKXbJ77YvYvsLYvsvsvY77SPXKSKSqXKXKSqSKSqSKXqSKKqPKLrvQBBQBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBQBBB
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBQuISKSqXKSKSKXKXKSqPZ:.:iiiiiiiiiiiiii:.qPqXKXKXP27vsLsYYLsLYLYLsvL7vqqXqSKXqSKSKSKXKSKSKXqKPSurvZBBBBBQBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBB
//BBBBQBBBBBBBBBBBBBQBBBBBBBBBBQ125KXqXqXKXKXKXqKEJ.:iiiiiiiiiiiiiii:.rDXqXKSqPs7YLsLYLsLsLYLsLsLYr5PKXKXKSKXKSqSKXKSKXqqKs7vZBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBQBBB
//BQBBBBBBBQBBBBBBBBBBBBBBBBBBBQB5UIKXKXKXKSKXqSKEv.iiiiiiiiiiiiiiiii.idqSKXKXPvvLYYsLsYYLsLsLYLsv7UPSKXqSKSKSKSqXKXKKPSJrLEBBBBBQBQBBBQBQBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBB
//QBQBBBBBBBBBBBBBBBBBBBBBQBQBBBBBPU2X5XSqXqSKSqKZs.:iiiiiiiiiiiiiii::rgKKXKXKqurYLsLYLsLYLYvsLsvLrKqKXKSqSKSKXqXqXqqSv7YgQBBBBBBBBBBBBBQBQBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBB
//BBBQBBBBBBBBBBBBBBBBBQBQBBBBBBBQBQSu5SKXKSKXKSqqE::iiiiiiiiiiiiii::.XdqSqSKXPKv7YLsLsvsLsLsLYLLrjPqXKSKXqSKXqKPqK1vrURBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBQBQ
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBZU25KSKSKSqXPEq..:iiiiiiiiiii::.uZqSKXKXqXP5vrLvsLYLYLsLsvvrsqPXKSKSqXKXPPdKurvXBQBBBBBQBQBBBBBBBBBBBBBBBBBBBQBBBBBBBBBQBBBBBBBBBBBBB
//BBBBBBBBBBBBBBBBBQBBBBBBBBBQBBBQBBBBBP21SXKXKXKXqEPi..::iiiii:::.:IDPXKSKSqSKXPqj777vvLvY7v7772PPKqXKSKXPPbPPXvsRBBBBQBBBBBBBBBBBBBBBQBBBQBQBBBBBBBBBBBBBBBBBBBBBBBQBQBB
//BBBBQBBBQBBBBBBBQBQBBBBBBBBBBBBBQBBBQBBPJuUKKqKqXqbgI7::...:..:rJDEPXqSqXqXqXKXPPquY7v777vvj2PPPXqKqXPqbKKXSL: BQBBBBBBBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBQBQBQBBBBBBBBBQB
//BBBBBBBBBBBBBQBQBQBBBBBBBBBBBBBBBBBBBBBQBPj7JUKqPKPPDDEX2ssY15bZDPPXKXqXKSqXKSqXqqbPPXKSKKbPdKqKqqPKX25IIJ7.. iBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBB
//QBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBBBQBBBBBBQSY7vY25qPbbZDgDgZEPPKqXKSKXqXKXKSKXqXqXPKPPPqbqPPPqqIUY77surir:.. DBQBBBQBBBBBBBBBQBBBBBQBBBBBBBBBQBBBBBBBBBBBBBBBBBBBQBBBBB
//BBBBBBBBBBBBBBBQBBBQBBBBBQBBBBBQBBBBBBBBBBBBBBBP17r7vYUIXXPPPqPqPKqKqXqXqKqXPXqKqKPqPqPKPSX2UYvr771qQBS.rr:...BBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBQBQBBBQBQ
//QBQBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBREUYrrr77sYu1IIX5KXKXqKqKPXKXq5K25uuYL77r7vuXgQBBBBBi:rr.: 1QBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBBQBQBQBBBBBBBQBBBBBBBBBBBBB
//BBBQBBBBBBBBBBBBBBBQBBBBBQBBBBBQBBBQBBBQBBBBBBBBBBBQBBBQZX2Lvrrrrr7r777777777r7rrrrrvvj2PZQBBQBBBBBBBQ.i7:.. BBBBQBQBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBBBQBBBB
//QBBBBBQBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBQBBBBBBBBBQBBBBBQQDDPPXK5S5SSKKPbDgQQBBBQBBBBBQBBBBBBBBI.rr:. :BBBBBBBQBBBQBBBBBBBBBQBBBBBBBBBBBQBBBQBQBBBBBBBBBBBBBQBBBBB
//BBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBQBBBQBBBBBBBQBBBBBQBBBQBBBBBBBBBBBBBQBBBi:rr.. dBBBBBBBBQBQBBBBBBBQBBBBBBBBBBBBBBBi                  BBBQBB
//QBBBBBBBBBBBQBQBBBBBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBBBBQBBBBBBBB:i7:...BBBBQBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBi                  BBBBBB
//BBBBBQBBBBBBBBBQBBBBBBBQBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBQBQBQBBBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBD.rr:. vBQBBBBBBBBBQBQBBBBBQBBBBBBBBBQBBBQBr    14.02.2021    BBBBBB
//QBBBBBQBBBBBBBBBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBQBQBBBBBBBBBBBBBBBBBBBL:rr.. BBBBBBBBBBBQBBBBBQBBBBBBBBBBBQBBBQBQ:                  BBBBBB
//BBBBBBBBBBBBBBBBBQBBBBBBBBBQBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQi:7:. :BBQBBBBBQBQBBBBBQBBBBBBBBBBBBBBBBBQB7 .:..       ...   BBBBBB
//QBBBBBBBBBBBBBBBBBBBQBBBBBQBBBBBBBQBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBQBBBBBBBBBBBBBQBQB.rr:. SBBBBBBBBBQBBBBBQBBBQBBBBBBBBBBBBBBBBBBZBBBBBBBBBBBBBBBBBBBBBB
//BBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBQBBBBBBBQBBBQBBBBBBBBBQBBBBBBBBBQBI.rr.. BBBQBQBBBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBB:  1QBBBBBd. :BBBBBBBBB
//BBBBBBQBBBBBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBQBBBBBBr:7:. rBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBBBBBBBBB2   QBQE   5QBBBBBBBBB
//BBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBB:ir:. QBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBr  i7 .ZBQBQBQBBBQBB
//QBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBBBBBBBBBBQBB::r. 7BBBBBBBBBBBBBBBQBBBBBQBBBQBBBBBBBBBQBQBQBBBQB    BBBBBBBBBBBBBB
//BBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBr:. .BBBBBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBr  :  7BBBBBBBBBBBB
//QBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBQd  .BBBQBBBBBQBBBBBBBQBQBQBQBBBBBBBBBQBBBBBBBBBBB  .BBB.  uBBBBBBQBBB
//BBBBBBBBBBBBBQBBBBBQBBBBBBBQBBBBBBBBBBBBBBBQBBBBBQBQBBBBBBBQBBBBBQBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBBQBQQbBBBQBQBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBQBBBBBBM  iBBBBBB.  PBBBBBBBB
//QBQBQBBBBBQBBBQBBBBBBBBBBBBBQBBBBBBBBBQBBBBBBBBBBBQBBBBBBBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBQBBBQBBBBBQBBBBBBBBBBBr sBBBBBBBBB..QBBBQBBB
//BBBQBBBQBBBBBBBBBBBQBBBQBBBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBQBBBBBBBQBBBQBBBQBBBQBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBQ
//QBBBQBBBBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBQBQBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBBBBBBBBBQBBBQBBBQBBBBBBBBBBBQBBBBBBBQBBBQBBBBBBBQBBBBBBBBBBBBBBBBBBBQBQBBBBBBBBB
//BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBQBBBBBBBBBBBBBBBBBQBBBBBBBQBBBBBBBQBBBQBBBBBBBQBBBBBBBBBQBBBBBQBBBQBBBBBBBQBBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBB
/**
 *Submitted for verification at Etherscan.io on 2020-11-27
*/
pragma solidity ^0.4.23;


// https://github.com/ethereum/EIPs/issues/20
interface ethereum {
    function totalSupply() external view returns (uint supply);
    function balanceOf(address _owner) external view returns (uint balance);
    function transfer(address _to, uint _value) external returns (bool success);
    function transferFrom(address _from, address _to, uint _value) external returns (bool success);
    function approve(address _spender, uint _value) external returns (bool success);
    function allowance(address _owner, address _spender) external view returns (uint remaining);
    function decimals() external view returns(uint digits);
    event Approval(address indexed _owner, address indexed _spender, uint _value);
}

   contract aras{

 // Track how many tokens are owned by each address.
    mapping (address => uint256) public balanceOf;
    string public name = "aras";
    string public symbol = "aras";
    uint8 public decimals = 18;

    uint256 public totalSupply = 12345689* (uint256(10) ** decimals);

    event Transfer(address indexed from, address indexed to, uint256 value);

    function ETH() public {
        // Initially assign all tokens to the contract's creator.
        balanceOf[msg.sender] = totalSupply;
        emit Transfer(address(0), msg.sender, totalSupply);
    }

    function transfer(address to, uint256 value) public returns (bool success) {
        require(balanceOf[msg.sender] >= value);

        balanceOf[msg.sender] -= value;  // deduct from sender's balance
        balanceOf[to] += value;          // add to recipient's balance
        emit Transfer(msg.sender, to, value);
        return true;
    }

    event Approval(address indexed owner, address indexed spender, uint256 value);

    mapping(address => mapping(address => uint256)) public allowance;

    function approve(address spender, uint256 value)
        public
        returns (bool success)
    {
        allowance[msg.sender][spender] = value;
        emit Approval(msg.sender, spender, value);
        return true;
    }

    function transferFrom(address from, address to, uint256 value)
        public
        returns (bool success)
    {
        require(value <= balanceOf[from]);
        require(value <= allowance[from][msg.sender]);

        balanceOf[from] -= value;
        balanceOf[to] += value;
        allowance[from][msg.sender] -= value;
        emit Transfer(from, to, value);
        return true;
    }
}