// SPDX-License-Identifier: GPL-2

pragma solidity ^0.8.0;

interface TraitDB {
	function viewTrait(uint256 _id) external view returns (string memory);
	function totalTraits() external view returns (uint256);
}

contract AttrAttitude is TraitDB {
    string[] attitude = [
				"Cautious"
			, "Calm"
			, "Lucid"
			, "Friendly"
			, "Gregarious"
			, "Garrulous "
			, "Kind"
			, "Courteous"
			, "Trustworthy"
			, "Loyal"
			, "Helpful"
			, "Obedient"
			, "Cheerful"
			, "Thrifty"
			, "Brave"
			, "Clean"
			, "Reverent"
			, "Pious"
			, "Querulous "
			, "Pleasant"
			, "Whinging"
			, "Depressed"
			, "Sad"
			, "Happy"
			, "Heady"
			, "Argumentative"
			, "Bitter"
			, "Gruff"
			, "Short"
			, "Puzzled"
			, "Unmoored"
			, "Unhinged"
			, "Stressed"
			, "Bubbly"
			, "Attractive"
			, "Jolly"
			, "Optimistic"
			, "Aggravated"
			, "Chilly"
			, "Dejected"
			, "Tired"
			, "Bashful"
			, "Awestruck"
			, "Easygoing"
			, "Horrified"
			, "Intelligent"
			, "Reluctant"
			, "Numb"
			, "Quizzical"
			, "Ravenous"
			, "Shy"
			, "Appreciative"
			, "Blissful"
			, "Contented"
			, "Ecstatic"
			, "Elated"
			, "Serene"
			, "Vivacious"
			, "Angry"
			, "Distressed"
			, "Glum"
			, "Gloomy"
			, "Grumpy"
			, "Grouchy"
			, "Miserable"
			, "Nervous"
			, "Mad"
			, "Moody"
			, "Sadistic"
			, "Sour"
			, "Selfish"
			, "Accepting"
			, "Indifferent"
			, "Cool"
			, "Earnest"
			, "Nostalgic"
			, "Passive"
			, "Reserved"
			, "Satisfied"
			, "Sentimental"
			, "Surprised"
			, "Sympathetic"
			, "Hopeful"
			, "Warm"
			, "Loving"
			, "Hurtful"
			, "Disgruntled"
			, "Guilty"
			, "Hostile"
			, "Obnoxious"
			, "Oppressive"
			, "Overbearing"
			, "Resentful"
			, "Sarcastic"
			, "Sardonic"
			, "Acerbic"
			, "Mysterious"
			, "Pragmatic"
			, "Regretful"
			, "Resigned"
			, "Solemn"
			, "Silly"
			, "Weird"
			, "Sick"
			, "Shocked"
			, "Rushed"
			, "Relieved"
			, "Rejuvenated"
			, "Rejected"
			, "Predatory"
			, "Peaceful"
			, "Giddy"
			, "Giggly"
			, "Infuriated"
			, "Naughty"
			, "Morose"
			, "Mischievous"
			, "Mellow"
			, "Melancholy"
			, "Listless"
			, "Lethargic"
			, "Lazy"
			, "Jubilant"
			, "Jealous"
			, "Ditzy"
			, "Groggy"
			, "High"
			, "Discontent"
			, "Frustrated"
			, "Flirty"
			, "Drunk"
			, "Crazy"
			, "Exhausted"
			, "Dismissive"
			, "Welcoming"
			, "Carefree"
			, "Curious"
			, "Nosy"
			, "Snide"
			, "Pugnacious"
			, "Confrontational"
			, "Deferential"
			, "Mild mannered"
			, "Incorrigible"
			, "Energized"
			, "Hangry"
			, "Callous"
			, "Caring"
			, "Gentle"
			, "Open-minded"
			, "Open-hearted"
			, "Loving, up to a point"
			, "Churlish"
			, "Aggressive "
			, "Combative"
			, "Inquisitive"
			, "Needs a drink"
			, "Couldn't give a shit"
			, "All out of shits to give"
			, "All out of gum"
			, "Ready to kick ass and chew gum"
			, "Ready to kick ass"
			, "Protective of lawn"
			, "Cranky"
			, "Chipper"
			, "Bored"
			, "Blank"
			, "Amused"
			, "Contemplative"
			, "Dignified"
			, "Dreamy"
			, "Empowered"
			, "Energetic"
			, "Enlightened"
			, "Enthralled"
			, "Exhilarated"
			, "Fulfilled"
			, "Hyper"
			, "Self-important"
			, "Light-hearted"
			, "Passionate"
			, "Playful"
			, "Apprehensive"
			, "Brooding"
			, "Cold"
			, "Confused"
			, "Critical"
			, "Crushed"
			, "Disappointed"
			, "Drained"
			, "Empty"
			, "Fatalistic"
			, "Frightened"
			, "Futile"
			, "Haunted"
			, "Heartbroken"
			, "Hesitant"
			, "Hopeless"
			, "Humiliated"
			, "Overwhelmed"
			, "Painful"
			, "Pensive"
			, "Perplexed"
			, "Powerless"
			, "Desperate"
			, "Remorseful"
			, "Restless"
			, "Scared"
			, "Skeptical"
			, "Serious"
			, "Somber"
			, "Threatened"
			, "Vengeful"
			, "Vulnerable"
			, "Festive"
			, "Tender"
			, "Panicked"
			, "Terrorized"
			, "Determined"
			, "Sinister"
			, "Cruel"
			, "Violent"
			, "Brutal"
			, "Rational"
			, "Affectionate"
			, "Aroused"
			, "Electrifying"
			, "Hollow"
			, "Feverish"
			, "Fiery"
			, "Frantic"
			, "Hot-blooded"
			, "Hectic"
			, "Hysterical"
			, "Impassioned"
			, "Livid"
			, "Obsessed"
			, "Soulful"
			, "Exasperated"
			, "Scornful"
			, "Wrathful"
			, "Spiteful"
			, "Mortified"
			, "Alarmed"
			, "Lustful"
			, "Defeated"
			, "Heartless"
			, "Inadequate"
			, "Insidious "
			, "Malicious"
			, "Meek"
			, "Oblivious"
			, "Petty"
			, "Repugnant"
			, "Shallow"
			, "Stingy"
			, "Sycophantic"
			, "Vulgar"
			, "Affable"
			, "Alluring"
			, "Charismatic"
			, "Dense"
			, "Understanding"
			, "Underwhelmed"
			, "Overwhelming"
			, "Frenzied"
			, "Bewildered"
			, "Cantankerous"
			, "Irreverent"
			, "Generous"
			, "Miserly"
			, "Wise"
			, "Foolish"
			, "Untethered"
			, "Frumious"
			, "Uffish "
			, "Beamish"
			, "Tickled"
			, "Ready to party"
			, "Fired up"
			, "Unconditionally loving "
			, "Infectiously joyous"
			, "Brainy"
			, "Vitriolic"
			, "Oafish"
			, "Magnetic"
			, "Jovial"
			, "Repulsive"
			, "Merciless"
			, "Ambitious"
			, "Captivating"
			, "Comical"
			, "Dazzling"
			, "Decisive"
			, "Dramatic"
			, "Stupid"
			, "Tranquil"
			, "Crass"
			, "Delirious"
			, "Desolate"
			, "Despicable"
			, "Diabolical"
			, "Dim-witted"
			, "Charming"
			, "Docile"
			, "Flattering"
			, "Hilarious"
			, "Influential"
			, "Sociable"
			, "Witty"
			, "Virtuous"
			, "Alarmist"
			, "Anguished"
			, "Arrogant"
			, "Chauvinist"
			, "Decadent"
			, "Depraved"
			, "Haughty"
			, "Flippant"
			, "Insufferable"
			, "Insulting"
			, "Menacing"
			, "Mournful"
			, "Patronising"
			, "Pompous"
			, "Pining"
			, "Repentant"
			, "Ruthless"
			, "Slovenly"
			, "Wistful "
			, "A little too cautious"
			, "A little too calm"
			, "A little too friendly"
			, "A little too kind"
			, "A little too courteous"
			, "A little too helpful"
			, "A little too obedient"
			, "A little too cheerful"
			, "A little too happy"
			, "A little too stressed"
			, "A little too bubbly"
			, "A little too optimistic"
			, "A little too easygoing"
			, "A little too shy"
			, "A little too grumpy"
			, "A little too grouchy"
			, "A little too miserable"
			, "A little too nervous"
			, "A little too moody"
			, "A little too selfish"
			, "A little too accepting"
			, "A little too cool"
			, "A little too earnest"
			, "A little too passive"
			, "A little too reserved"
			, "A little too self-satisfied"
			, "A little too sentimental"
			, "A little too sympathetic"
			, "A little too hopeful"
			, "A little too warm"
			, "A little too loving"
			, "A little too hostile"
			, "A little too obnoxious"
			, "A little too overbearing"
			, "A little too resentful"
			, "A little too sarcastic"
			, "A little too sardonic"
			, "A little too mysterious"
			, "A little too pragmatic"
			, "A little too silly"
			, "A little too weird"
			, "A little too predatory"
			, "A little too naughty"
			, "A little too mellow"
			, "A little too listless"
			, "A little too lazy"
			, "A little too jealous"
			, "A little too flirty"
			, "A little too drunk"
			, "A little too crazy"
			, "A little too welcoming"
			, "A little too carefree"
			, "A little too curious"
			, "A little too nosy"
			, "A little too open-minded"
			, "A little too inquisitive"
			, "A little too amused"
			, "A little too hyper"
			, "A little too playful"
			, "A little too apprehensive"
			, "A little too critical"
			, "A little too hesitant"
			, "A little too pensive"
			, "A little too desperate"
			, "A little too restless"
			, "A little too scared"
			, "A little too skeptical"
			, "A little too serious"
			, "A little too somber"
			, "A little too vulnerable"
			, "A little too determined"
			, "A little too sinister"
			, "A little too cruel"
			, "A little too violent"
			, "A little too rational"
			, "A little too affectionate"
			, "A little too aroused"
			, "A little too frantic"
			, "A little too hot-blooded"
			, "A little too obsessed"
			, "A little too vulgar"
			, "A little too charismatic"
			, "Suspecting"
			, "Suspicious"
			, "Sagacious"
			, "Antic"
			, "Caustic"
			, "Contumacious"
			, "Bellicose"
			, "Didactic"
			, "Feckless"
			, "Guileless"
			, "Boorish"
			, "Mendacious"
			, "Insidious"
			, "Zealous"
			, "Fastidious"
			, "Taciturn"
			, "Querulous"
			, "Puckish"
			, "Petulant"
			, "Racist"
			, "Sexist"
			, "Wondering what you are doing here"
			, "Touched by your attention"
			, "Attracted to you "
			, "Horny"
			, "Manic"
			, "Indignant"
			, "Irate"
			, "Meditative"
			, "Judicious"
			, "Not in the mood"
			, "Just can't "
			, "Wants to hear all about it"
			, "Has a comeback for everything"
			, "So you're the expert now?"
			, "Go away"
			, "Please go on"
			, "With pleasure"
			, "So intrigued"
			, "Utterly spellbound"
			, "Can't get enough"
			, "If it don't look rare, don't care"
		];
 
	function viewTrait(uint256 _id) external override view returns (string memory) {
		return attitude[_id];
	}
	
	function totalTraits() external override view returns (uint256) {
		return attitude.length;
	}
}

