// SPDX-License-Identifier: GPL-2

pragma solidity ^0.8.0;

interface TraitDB {
    function viewTrait(uint256 _id) external view returns (string memory);
    function totalTraits() external view returns (uint256);
}

contract AttrHabitus is TraitDB {
    string[205] habitus = [
    "Upright"
  , "Hunched"
  , "Flexible"
  , "Confident"
  , "Stiff"
  , "Weak"
  , "Strong"
  , "Quiet"
  , "Battle-hardened"
  , "Duty-bound"
  , "Pained"
  , "Slow"
  , "Fumbling"
  , "Knavish"
  , "Bent"
  , "Gawky"
  , "Fat"
  , "Clumsy"
  , "Elegant"
  , "Striving"
  , "Dangerous"
  , "Intimidating"
  , "Huge"
  , "Tiny"
  , "Miniature"
  , "Miniscule"
  , "Low class"
  , "Muscular"
  , "Fit"
  , "Slender"
  , "Approachable"
  , "Unapproachable"
  , "Leering"
  , "Peering"
  , "Cryptic"
  , "Flailing"
  , "Wild"
  , "Uncontrollable"
  , "Feral"
  , "Untamed"
  , "Tame"
  , "Civilized"
  , "Mourning"
  , "Enraged"
  , "Frenetic"
  , "Fanatic"
  , "Lonely"
  , "Asleep"
  , "Hyped"
  , "Gaunt"
  , "Thin"
  , "Thick"
  , "Thick-headed"
  , "Thin-skinned"
  , "Manipulable"
  , "Malleable"
  , "Easily convinced"
  , "Unintelligent"
  , "Of the South"
  , "Of the North"
  , "Inhuman"
  , "Unnatural"
  , "Diseased"
  , "Standing against tree"
  , "Sitting on grass"
  , "Micturating"
  , "Scanning the horizon"
  , "Arms crossed"
  , "Hands on hips"
  , "Right hip cocked"
  , "Tilted head"
  , "Proper"
  , "Bonebroken"
  , "Squinting"
  , "Leprotic"
  , "Morbidly obese"
  , "Covered in massive scars"
  , "Charming smile"
  , "Albino"
  , "Covered in tattoos"
  , "Rosy cheeked"
  , "Frumpy "
  , "Lanky"
  , "Wiry"
  , "Cross-eyed"
  , "Shaved eyebrows "
  , "Extremely clean"
  , "Innocent eyes"
  , "Smells musty"
  , "Extremely pale"
  , "Hard eyes"
  , "Sunken eyes"
  , "Bulging eyes"
  , "Protruding teeth"
  , "Heavy-lidded eyes"
  , "Freckles everywhere "
  , "Beady eyes"
  , "Birdface"
  , "Cat-like movements"
  , "Steely eyes"
  , "Sweeping eyelashes"
  , "Arched eyebrows"
  , "Bushy eyebrows"
  , "Drooping skin"
  , "Smooth, clear skin"
  , "Dry, flaky skin"
  , "Scales instead of skin"
  , "Flawless skin"
  , "Pockmarked "
  , "Weather-beaten face"
  , "Wolfish smile"
  , "Angular cheekbones"
  , "Weak chin"
  , "Protruding adam's apple"
  , "Button nose"
  , "Aquiline Roman nose"
  , "Bulbous nose "
  , "Gleaming white teeth"
  , "Unkempt hair"
  , "Neatly combed hair "
  , "Brawny arms"
  , "Barrel-chested"
  , "Pot-bellied"
  , "Voluptuous"
  , "Emaciated"
  , "Herculean figure"
  , "Vacant gray eyes "
  , "Shaking shoulders "
  , "Dirt worked into the lines of face"
  , "Jeering look"
  , "Large ears, uncut hair"
  , "Wary, thoughtful dark eyes "
  , "Gracious"
  , "Tense"
  , "Proud"
  , "Withdrawn"
  , "Bold"
  , "Cunning"
  , "Intense"
  , "Greedy"
  , "Famished"
  , "Frank"
  , "Sly"
  , "Tawdry"
  , "Inspiring"
  , "Sexy"
  , "Enticing"
  , "Observant"
  , "Long suffering"
  , "Calculated"
  , "Refined"
  , "Gull"
  , "Piercing"
  , "Deranged"
  , "Dirty"
  , "Malnourished"
  , "Rotund"
  , "Gigantic"
  , "Sunken"
  , "Inebriated"
  , "Sober"
  , "Tumescent"
  , "Expecting"
  , "Tormented"
  , "Uncomfortable"
  , "Quietly reassuring smile"
  , "Old man's scowl"
  , "Mouth like a knife "
  , "Bold as a wild buffalo "
  , "Reckless "
  , "Voice soft as honey"
  , "Deranged clothing, tangled hair"
  , "Greasy, long hair"
  , "Crumpled and freckled face "
  , "Foaming with rage"
  , "Remarkably cold eyes "
  , "Stealthy, faint smile"
  , "Long chin and buckteeth"
  , "Large and dull eyes"
  , "Glassy eyed"
  , "Has a face like sunshine"
  , "Still as a stone"
  , "Long platinum blond hair "
  , "Long hair like black smoke"
  , "Gray, slippery skin"
  , "Wide mouth full of needle teeth"
  , "Shrunken and hunched"
  , "Goose-egg sized and milky white eyes "
  , "Vampire-white skin"
  , "Stubborn mouth and chin"
  , "Hardened, brutal face"
  , "Hand clenched, knuckles white"
  , "Sweating "
  , "Hidden, graceful strength"
  , "Beefy, carries weight like a weapon"
  , "Perfectly balanced movements"
  , "Eyes flash and glitter with savagery "
  , "Rotting"
  , "Peeling"
  , "Necrotic"
  , "Stabbed"
  , "Bleeding out"
  , "Impaled"
  ];
  
   
    function viewTrait(uint256 _id) external override view returns (string memory) {
        return habitus[_id];
    }
    
    function totalTraits() external override view returns (uint256) {
        return habitus.length;
    }
}

{
  "optimizer": {
    "enabled": true,
    "runs": 20
  },
  "outputSelection": {
    "*": {
      "*": [
        "evm.bytecode",
        "evm.deployedBytecode",
        "abi"
      ]
    }
  },
  "libraries": {}
}