/**
 *Submitted for verification at Etherscan.io on 2020-05-26
*/

pragma solidity 0.6.0;
contract Takemiya_Makoto {
string public inscription =
"|___༻ 8 ༄___|  ////////+///+++++oss:+++ooooosososssyysyysso+o+////////://:::/::-+dhhdddmmmmms++/:--..`````"
"::://///:/:///////+///++/++++++++osyshdmmdddmmmdmmmmmmmmmmmmmmddhys+/://:::/:/::.odhhddddmmmms++/:--...`````"
"/://///////////+++++++++++++osydddmNNmmmmmmmddmmNNNNmNNNNNNNmmmmmmmmdys++///:::-.ohhhddddmmmms++/:--...`````"
"//////////////+++++o++++++oymNmmNNNNNNNNNNNNNNNNNmNNNNNNNNmmmmmmmmmmmmmdddhyo/:-.ohhyyddddmmmo++/:-....`````"
"//////+///+/+++++++++++oshdmNNNNNmmdddmNNNNNNMMMNNNNNNNNNNNmmmmmddmmNNmmmmmNmdho-+ysyshddddmdo++/:--...`````"
"/////++++++/++++++++ohdmmmmmmNNNmmmmmNmNNNNNNNMNNNNNNNNNNNmdmmmmmmmmmmmNNNmmmmNmdhysosyhdhdmd+///::-...`````"
"/////+/+++++++++++sdmmNNNmmNNNNNNNNmmmmmmmmmNNmmmmmdmmmNNNNmmmmmmmmmmmmmmmNNmmmNNNmmhsssyhhmd+///::--..`````"
"//////+++++++++oshmmNNNNmmNMMMNNNNNNNNmmmmmmdmmmmmmmmdmmmmmmmmmmdmmmmmmmmmmmNmmNNNNNmmhyyyhdh////:---...````"
"/++////+++++oshdmmmNNNmmNNMMNNNNNNNNNNNNNNNmmmdhhddmmmNNmmmmddmmmmmmmNNNmmmmNNNNNNNNNmNmdhyhh////::--....```"
"//////////+yhdmmmNNNmmmmNMNNNNNNNNmmNNNNNNNNNNNmddmmmmmmNNNmmmdmmNNNNNNNNNNNmNNNNNNNNNNmmmmdy///::---......`"
"////////+shdmNNmmNNmmNmNNNNNNNNNNNmdmmNNmmmmNNNMNNmmdddmmmmmmmNNNNNNNNNNNNNNNNNNNNNmmNNNmmmmmho+::---......."
"////////ohdmNNdmNNNNNmmmNNmNNNmNNmmmdddmmmmddmmNNNNmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNmmNmmmNmmmho/:---......"
"///////osdNNNmmmNNNmmdmmmmmmmmmdddddmdddhhhhhddmmmNmmmmmmmmNNNNNNNNNNNNNNNNNNNNMNNNNNNNNmNmNNmmmdy/:--......"
"//////oohmNNNNNNNNmdhdmmddddddhyyyyhhyssooosshhhdmmmmdddddmmmNNNNNNNNNNNNNNNNNNNMNNNNmmNmmmmmNmmmdh+:---...-"
"/////lshmNNNNNNNmmdhhmddddhyyso++oooo+/////++oyyshdmmdsyhddddmmmmmNNNNNNNNNNNNNNNNMMNNNmmmmmmmNNmmmho:-----."
"/////oddmNNmmmmNdhhyhdhhdhssoo++++++++//////+++sssydmmysyhhdhdddmmmmNNNNNNNNNNNNNNNNNMMNNmmmmmmNNmmmho:-:..."
"/////dddNmddmmdhhhyyhyhhysoo++/++++/////////+/++oysyhdmyssyyhhhddddmmmNNNNNNNNNmNNNNNNNNNNNmmmmmmNmmmho:----"
"////mddmmhhhdmhhhdhyyyhsoo++///////:://///::////+osyyyddssssyyyyhdddmmmNNNNNNNNmmNNNNNNNNNNNNmNmdmmNmdy/----"
"////dddmhhhddhddmddyyyo+++////:::::::/::::::///+++osyyhdhsssssssssyhdddmmNNNNNNNNmmmNNNNNNNNNNNNmmmmNmdo----"
"////ddddhdmdhhmmmmdyso+///:://::::::::::::::::////+oosshhsssssoooosssyyhhdmmmNNNNNmmmNNNNNNNNNNNNmmmNmdh/--."
"////hhddmmddmmmmmhso+:::::-::::::::::::::::::////+++oooyysoooooooossssyyhhhhdmNNNNNddmNNNNNNNNNNNmmNmdds/--"
"////mdhdmmmmmmmmmhy+/::::::-------:::::::::://://+++++ooooooooo+oooooosssyyyyyyhddmNNmmmNNNNNNNNNNNmNNddo/:-"
"////mdyhmmmmmmmdyso/:--:----------::::::://://////++++++oo++o++oooooooosssssssssssyhdmNmNNNNNmNNNNNmNNmdo:--"
"////mdydmdmmhdhys+/:-----------:::::::://///////+//++++++o+++oooossoooosssssooooossshdmNNNNNNmmNNmNmNNmdo:--"
"////dyhddddhhdhyso/-----.------:::::::///////////////++++o++ooooooooossssssssoooooosyhdmmNNNNNmmNmmNmNmd+---"
"////dydsshhhhhhhy+:----.-------:::::::////+////+//////++++++++o+oooosssssssssssssssssyhdmNNNNNmmNNdNmmmdo:--"
"////mhdmddhhhhhhs+:---.-----------:::::://////+++//////+++++oooooooossosssssssssssssssydmNNNNNNmNNmmmmmdo/--"
"////Nmddmddddhdhs/:------.----------::::////+/+++///////++++o++ooooosooossssssssssssssydmNNNNNNmNNNNmmmh+:--"
"////Nmmdddmmdddhs/------------------:::::///////////:/://++++o+++ooosooooosssssssssysyyhdNNNNNNNNNNNNmmh+:--"
"////Nmmdddmmdddds:-:-------::::--:::////////////////:///+++ooooooossssosssssyysssyyyyyyyhmNNNNNNNNNNNmms:---"
"///|NNddddmmdmmho/:::::/++//++++o+ossooooo+////////////+++osssyyhhhhhhhhhhhhhhhhhyyyyyyyhmNMMNNNNNNNNmd+----"
"///|NNddmdddmmmh+:://+syssyhhddddddhhyysss++////////++++oosyyhddmmmNNNNNNmmmmmmmdddhhyyyhdmNMMNmNNNNNNd/----"
"////NmhhmmhdmmNd+:+osyyyyyyhhddddmmmmdhyysoo+//////+++ooosyhddmmNNNmmmmdddmmmmmmmmddhhyyydmNMMNmNNNNNNh/----"
"///lNmhhdmddmNNd+/osoo+++/+++oosyyyhhhyyssoo+//////+ossssyhdddddddhyyssssssyyhhhdddddhhyyhmNMMNmNNNmmds:----"
"//L/Nmdhhdddmmmd+/o+/::://+oyydddmddddhyyso+/:::://+syyhhdddddddhhyhhddddhhhyyyhhhhhdhhyyhdNMMNNNNmhdd+-----"
"////-mdhyhhdmmdh///::/+ossyysdshNdmdhhhyyso+/:---:/osyhdddmmmdddhyoysmNmmNmdmmdddhhhhhhhyhdNMMNNNNddmds-----"
"////-`dhy+sdmmdy/:::/+syyso//yhdmddhyyyys++/+/:--:/oshdddmmdddmdyo/ohdmdmmhhdmmmdddhhhhhyhdmNMNNNNmhmdo-----"
"////{mddh+:yddhy/:--:/++/////+osssyyyysoo+/++/:::/+oyhdddmdddhhhyssssyyhhyhhhhdddddhhyyyyyhmNNNNNNdhddo:////"
"/////mddho-:yhhy:----:::::::://++ossssoooo+++/:::/+syhhdddmmdhhyyssoooossyhhhhhhhhhhyyyyyyhmNNNNNNdydh+//++/"
"///:mddddo--/shs:----:::----:::://+++ooo++///:::/++syhhdddddddhyysssooosssyyyyhhhhhyyyyyyyhmNNNNNmhyhh++o+++"
"////'ddddho--:+hs:----:---------::://+++///:::-:://+syhhhdddddhhhysssssooossyyyyhhyyyyyyyyyhmNNNNmdhhhhhhdddh"
"///''dddh/-:/+os/---------------:://///:::----:::/+oyhhhhhhhhhhhyyyssssssssyyyyyyyyyyyyhhhhmNmddddddhhhhhddd"
"/////ddh:-:+o+o+--------------::::::::--------::/+syhhhhhhhhhhhyyyyssssssssyyyysyyyyyhhhhdmmmhhmmmdhhhhhdddh"
"s///::hddy:.-:oy+:---.--------::::::::---------::/+syhhhhhhhhhhhyyyyysssssssyyyyyyyyhhhhhhdmmddmmmdhhhhhhdhd"
"++// yhhy+-...:++::-----------:::-::-::------::::/+oyhhhhddhhhhhyyyyyysssssyyyyyyhhhhhhhhhdmmdmdhhhhhhhhhddh"
"+//+oyhhyo/-....-::-------:-:---------:---:::::::/+osyhhddddhhhhyyyyyysyyyyyyyyhhhhhhhhhhhdmddhhyyhhhhhddhdh"
"+///+shhhso/-...-:::-----:----------:::-:::::::://+osyhhdddddddhhyyyyyyyyyyyyyhhhhhhhhhdddddhhhhhhhhhhddhhhd"
"+///+shhhso+/:----/::---------------:::::::::::::/+osyhhhhdddddhhhhyyyyyyyyyyhhhhhhhhhddddddhhhhhhhhhhhdhhhh"
"////+syhhso+///////::-------------::::::::::::::/++osyhddhhhdddhhhhyyyyyyyyhhhhhhhhhhdddddddhhhhhhhhhdhhdddh"
"////+oyhhso+///////::-------------::::/::/+syo++oosyhdmmNmdhdddhhhysyssyyyyhhhhhhhhhddddddhooo+/:///////////"
"/////oyyhys+///////::-------.-----::::::://++///+ssydddmmdddddhhhyysssyyyyhhhhhhhhhddddddds-----------------"
"/////+syyyoo+//////::------------::::::::://::://+shdhhdddddhhhyyyssssyyyyhhhhhhhhhdddhddh+-----------------"
"/////+syyyso+//////:::-----------:::::::::::/:://ossssyhdhhhhhyyyyyyyyyyyhhhhhhhhhhddhhddh:-----------------"
"/////+syyyso+///////:------------:::::::://///:/+ss+/+syhhhhhyyyyyyyyyyhhhhhhhhhddddddhdds------------------"
"/////+syyyso+///////:---------:--:::///::::::::/+oo+//osyyyyyyyyyyyyyyhhhhhhhhhhhhddhhhdd+.-.---------------"
"/////+oyyyso++///////-----------:::////::::::::/++o++osyyyyhhhhhyyyyyyhhhhhhddddhhhhhhhdd:...---.-----------"
"/////+oyyysoo+///////:----------::/+ooo////+oooossoshhhhhhhhdddddhhyyyyhhhhddddhhdddhhhdy..........---------"
"//////oyyysso+/////+/::-------:::/osyhysssssyyyyyyyhdddddmmmmmmmmmmhyssyhhddddddddddhhdh/..........---------"
"/////+osyyyso++/////+/:-:--::-:::/+oo+/+ooo+++oossyyyyyyhhhdddd  the Noir is good wine -..........----------"
"//////+syyyso+/////////::::::::::/++/:::://///++oosssssyyyhhddddddhhyyyyhdddddddddddddh:............-------."
"//////+syyysoo+///+/////:::::::::////::::::///++ossssssyyyhhhhhhhdhhhhhhdddddddddddddd+..............--.----"
"//////+oyyysoo++////////+/::::::://///::::///+oosyysyyyyyyyhhhhhhhhhhhhdddddddddddddds-..................---"
"//////+oyyysoo++////+//:so///::::///////////++ossyssyyysyyyhhhhhhhhhhdddddddddddddddd+-................-----"
"//////+osyysso++///////:ss////:::://:///////++++oooossssyyyhhhhhhhhdddddddddddddddddh:-...................--"
"//////+osyyyso++////+//:ys:/++/////:::::::/::////+oooossyyyhhhhhhdddddddddddddddddddy-...................---"
"//////+osyyysoo++///+//:ys/:/++/////:::::::::::/++ooooossyyhhdddddddddmddddddmddddddo-.................---.."
"//////+osyyysoo+++/////:ss/:::+o+++//::::::::::/+ossooossyyhdddddddddmmmmmmmmmdddddd+......................."
"//////+osyyyssoo++++///:ss/:--:++o+++///::////+oosyyssossyhdddddddmmmmmmmmmmmddddhdd:......................."
"//////++oyyyssoo++++++/:syo:---:/+ooo+++////++ossyyyssssyyhhddmmmmmmmmmmmmmdddddhhdd/......................."
"//////+ooyyyssoo+++++++:ymy:----::++oooooooosssyyyyyysyyhhhddmmmmmmmmmmmmmddddhhhhddhys+:-.................."
"///////+oyyysssoo++++++sNh-/:----::/+++ooosyyyyhhhhyyhhhhdddmmmmmmmmmmmmdddddhhhhhhhdmyhmdo:................"
"///////+osyyssoooo+oo+ymm+`//::--:::://+ooosssyyyyyhhhhhdddddmmmmmmmmdddddhhhhhhhddhdNdshNNd+-.............."
"///////+osyyyssoooooohmmm:`//::-:::::::://+ossyyyyyyhhddddddmmmmdddddddddhhhhdhhdddhdNNyomMNNh:............."
"///////+osyyysosoooodmmmm/`-/::-::::::-:::::://+oosyyyhhhhhddhddddddddddhhhhhhdddddhdNdosymMNNd+............"
"///////+osyyysssoosmNmmmNo``//::::-:::--::::::::://+ooosssyhhhddddddddhhhhhhhhddddhdmhoosshNMNNmo::::-------"
"//+//+++osyyyssooymNmmmmmd. .//:::::::--:::--:::-::/+oosyyhhddddhddddhhhhhhhdddddddmyooosyymNNNNmo/+++//////"
"//+/++++osyyssooyNNmmmmmmNo  -//::::::--------:::-:/+ssyhdddddddhhhhhhhyyhhhdddddmds+oossyhmNNNNNd+---------"
"/+++++++osyyssoymmNmmmmmmmd- `:/:::::::---------::/+oyhddddddhhhhhhhhyyyhhhdddddmh+/+ossyhmNNNNNNNd+::::----"
"++++++++ossysoymNmNmmmmmmmNy.  :/:::::::--------::/+syddddddhhhhhhhhyyyhhhdddddms//osssyhmNNNNNNNNNmssssssss"
"++++++++oosyssmNNNNmmmmmmmmmy` `/+::::::::---:::::/oyhddddhhhhhhhhhyyyyhhhdddmd+/+osyyhdmNNNNNNNNNNNmhhddddd"
"++++++++oossymNNmmmmmmmmmmmNm/  `os:::::::::--:::/+oyhhddhhhhhhhhhyyyyhhhdddms/+ossyyhdmNNNNNNNNNNNNNNhyhhhh"
"oo+oosyyhmmNmmmmmmmmmmmmmmmNNs`  `hy/:://::::::::/+osyyyyyhhhhhhyyyyyyhhhddmo:+syyyhhdmNNNNMNNNMNNNNNNNhyyyy"
"yhhdmmmmNMMmmmmmmmmmmmmmmmmmNm/   -dho//:::::::://+osssssyyhhhyyyyyyyhhdddd+/+osyhhhdNNNNNNNMMMMMMMMNNNNhyyy"
"NNNNNmmNMMNmmmmmmmmmmmmmmmmmNNh.   :mds+++//::://++oooosssyyyyysssyyhdddmd+/sssyyhdmNNNNNMMMMMMMMMNNNNNNmyyy"
"NNNNmmNMMNmmmmmmmmmmmmmmmmmmmNmo`   /mmhso++/////++++ooosssyssooosyhhddmd++syyyyydmNNNNNNNMMMMNNNNNNNNNNNhsy"
"NNmmmNNMMNmmmmmmmmmmmmmmmmmmmNNd/`  `smmdysooo+++++++ooooosso++ooshddmmmo/syyhhhdmNNNNNNNNNNMNNNNNNNNNNNNNmd"
"mmmmNMMNmmmmmmmmmmmmmmmmNNmmmNNh:   .hNmdhysssooooo+oooooo+++++syddmmmo:osyyhhdNNNNNMMMNNNNNNNNNNNNNNNNNNNNN"
"mmmmmNMMNmmmmmmmmmmmmmmmNNmmmmNNms`   -mmmmdhhyyyssooo+o+++///++shdmmms-/syyyhmNNMMMMMMNNNNNNNNNNNNNNNNNNNNM"
"mmmmNNMNNmmmmmmmmmmmmmmmmmmmmmNNNd:    /mmmmddhhhyysssoo+/////+shdmmmo-:+oyyhmNNMMNNNNNNNNNNNNNNNNNNNNNNNNNM"
"ddmmNMMNNmmmmmmmmmmmmmmmmmmmNmmNNNs.   `+mmmmmddhhhyysoo+////+shdmmmo.:+osyhmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMM"
"dmmmNMMMNmmmmmmmmmmmmmmmmmmmNNNNNNms.   `ommmmmddhhhyysso+++oshdmmd+.-/oyyhmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMN"
"dmmNNMMMNmmmmmmmdmmmmmmmmNNNNmmmmNNdo`   `smmmmmmddhhyyssoooshdddd/`-/osyhmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMN"
"mmNMMMMNNmmmmdmmmmmmmmmNNNNmmmmmmNNh/`   .yNmmmmmdddhyyyssyyhddh/`.:+oyymNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMNN"
"dmNNMMMMNNmmmmmmmmmmmmNNNmmmmmmmmmNNmy:    -dmmmmmmddhhhhyyhhddh:`.:/osydmNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMNN"
"mmNNMMMMMNNmmmmmmmmmmmmmmmmmmmmmmmNNNdy-    :hmmmmmmddhhhhhhddh/`.:+oyydNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMNNN"
"mNNNMMMMMNNmmmmmmmmmmmmmmmmmmmmmmmmNNmhs-    :dmmmmmddhhhhdddh:`.:/oyydmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMNNNN"
"mNNNMMMMMNNmmmmmmmmmmmmmmmmmmmmmmmmNNNmhs.    /dmmmmmdddddddh:`.-/osyhmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMNNNNm"
"NNNNMMMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmNNNhhs.    /dmmmmmddmddd:`.:/osyhmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMNNNNmm"
"NNNNMMMMMNNmmmmmmmmmmmmmmmmmmmmmmmmmmNNmhh+`    /mNmmmmmmmd- .:+osyhmmNNNNNNNNNNNNNNNNNNNNNNNNNNMNNMMMNNNNmm"
"NNNNMMMMMNNNmmmmmmmmmmmmmmmmmmmmmmmmmmNNdhy/     omNmmmmmd:`.-/+syhmNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMNNNmmm"
"NNNNMMMMMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNhhy-    `sNNmNNd:`.:/+syhmNNNNNNNNNNNNNNNNNNNNNNNNNNNMNMMMMMNNNmmmm"
"NNNNMMMMMMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmNNdhh+.    .yNNNm:-://+oyhmNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMNMMMNNNNmmmm"
"NNNNMMMMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNhhy/`    -dNd:`-/+oosydNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMNNNNNmmmm"
;
}