/**
 *Submitted for verification at Etherscan.io on 2020-04-21
*/

pragma solidity 0.6.0;
contract Pierre_Marie_Riviere {
string public inscription =
"mdys:.``sNmho-``oNNNNNNNms:`  `dNNNNNmmdho-``oNNmmmdo-/NNNmmd+.``-yhhddddhso/-``.+:.``/NNmhs+```:yddssyd+.-hMNNmds//ymmm"
"mdhs:` `oNmho:``+NNNNNNNmho-` `hNNNNNNNmmds/-oNNmmmh+-+NNNmddo-``-syyhdhhhso/-``.+:.``:mNmhs+. `:sddyoyh/.-hNNmdhs//sddd"
"mmdy/.` +Nmho-``/NNNNNNNmy/.`  +NNmmNNNmdhs+:yNNmmds:.oNmNmmds-``.oyyddhhyso/.``.+/-``:mNmhs+. `-sddhsyh:`.hNNmdhs//sddd"
"mddy/.` /mmds:``:NNmmmddho:.`  -NNNNNNNmddo-/dNNmmdo-.sNNhdhhs-``.oyydmdhys+/.``.+/-``:mNmho+.  .sdmdyyy:`.yNNmdhs::sddd"
"Nddy+-` :mmms:.`:NNNmmmmmhy+:. -NNmmmmmddds:/dNNmmy/.`sNNs-ods-.`.oyydddhyso/-``.+/-``-mNNdyo-` .sdddyyy:`.yNmmhy+-:ohdd"
"Nmmdo-` -mNms:.`:NNNNNmdmdhs/``:N+smmNmdsdy::yNNdyy/``-ssh+.yy:.`.+ssyhdhhyo/-``.+/-``.dNNNhs-` `oddhyyy:`.ymmhs+:--+yhh"
"mmmho:``.mNmy/.`-NMNNNNmmdhs/.`+m.odmNNmhyy/-oddo:o-``-odNh-yh/.``-//ohdhhyo+-```++-``.dNNNmh/` `+hddyyy/`.smmhs+:--+yyh"
"Nmmhs:.`.mNmh+-`-mMNNNNmmdhy+-.oNy./omNmdd+-.-:-./+-.`-hdho/o+:.```::/oss+oo+-```oo:```hMMNNmh-``/hddhyy/`.ommdys/--+yhh"
"Nmmds/. `dNmh+-`-mMNNNNmmhss+-.+NNo`.ommhy+-.:o+oo+:...///....`````::--/+/oo/-```os/.``yMMNNNms.`/hddhyy/..ommdhs/--+hdh"
"Nmmds/.``hNmh+-`.dMNNNmNNmhs/.`/mmh:``oysso-.:ooo+:-.....`````  ```.....-..---` `/s/.``yNNNNNms..+dddhys/..+mmdyo/.-+hdd"
"mmmdy/.``sNmh+-``hMNNNNNNmhy+.`:hddy:``os++--:::-::///:/:..-.-.``    `--.``     `:o/.``sNmmNmd+..odddhyy+.`/dmdyo/.-+hdd"
"mNmdy/.` oNmh+:``yMNNNNNNmds/.`-syooh/.:so++++o+:/oosooo+++yyy+:.``   ```````    ``-.``ommmmmd/`.+hddhyyo.`:dmhso/--/hdd"
"mmmdy+.` +Nmdo:``sMNNmNNmsso:.`.sdyhys:-/hddhhdyyysyoshdddmNmho+:-..` ``..`..```      `omdddds-`.+hddhhys-`-hmhs+:../ydd"
"mNmdy+.` :Nmho:.`sMNNhmmd+::-.``:o+o/..:hNmmmddmhoshdmmmNNMmhhdhho::/-.----.--.-``    `:hhdmdo.`.+hdddhhs-`-ymdyo:..:ydd"
"NNmdy+-` -Nmho:.`oNNmysh//-.````.--```:yNdmmmmmmys+dNNNNMNNdmdmmdhys+osyys+:-```      `-hhdmdo.`.+hhdhhys-`.ymdho/../ydd"
"NNNmho:` -mmds:.`+Nhdy-.`-.``````.``:ohmdhNNNmmdmmdhmNNNNNhyddmmmhhh+://::--```        `-sdmh+.``/yhhhhys:`.smdho/-.:ydd"
"NNNmdo:` .mNdy/.`/Ndsho:.```  ``...:shho+dNNNNNNNNNNMMNMNNdosdNmhysyyyyyo:`              .sdh/.`./yhhhhys:``+mdyo/-.:ydd"
"NNNmdo:` `dmso/.`/NNyhd+//.`  ``..:os+:-omNNNNMMMMMMMMMMMMNNmmmmmmmdmdmds/.               .os/.`./yyhhhys:``/mdys+--:ymm"
"NNNNds/. `hs-:/.`:mNNdy+/:-```...-/+o/+hNMMMMMMMMMMMMMMMMMMMMMNNNMMmmhmmNds+.`             ./:```:oyhhhyy/``/mdhy+:-:ymm"
"NMNNdy+.``oo.`..`:mmhhs+::....-://+ydmNMMMMMMMMNMMMMMMMMMMMMMMMMMMMNNNNMMMNmo-:```          `.```-+oyhhyy/``:dmdyo/-:ymm"
"NNNNdy/.``sho-````+hyo+/++/++ooshdmNNNMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMNNMMMMMNyhy//:-`````      ```-+sossss/``-hmdys+:/hmm"
"NNNNmy+-``sdhy/.``-::://+ossyhmmmNNNNMNNNmdhhdmNNNNNNNNNNNNNMMMMMMMMMMMNNMNNmddddsd+.-:/o++:.`  `.:+ohhss+.`.hmdyo/:/hNN"
"NNNNmho:``+dy+:.``-s/-:ooosyhdNNMMMMNmmhyo+//:/ooossssssyhhdmmNNNNMMMNNmNNNNNMMNNmMNyohysso++o/`  `:/yyss+.`-ymdyo/:/hNN"
"NNNNmho:` :d/-.```:-::/+sshdmNNMMMNmhy+:-...```...-----:://++syhhhdddddhdmNmmNMMMNMNNdNNdyho:-:`  `../ooso-`-ymdys/:/hNN"
"NNNNmho:` .o-....`:/oshdmNNNNMMMMNms+:-..```````````.......--:/+//+++oooshdhhmNNMMMMMmNMMNmmd/-`  `.``..:+:..smdyo/-:smN"
"NNNNmho:` .++::-..:shmmNNNNNNMMMNdo:-...````````````.``......-------::://+ooossmNMNNMNMMMMNmdo``` `.:..----..omdyo/--omm"
"NNNNmds/` .dds+-.:ymmNNMMMMMMMMMd/-...``````````````````......---------:::////-omNNMMNMMMMNdy+.`.-.-:::/:::..oddys/--odm"
"NNNmmds+.`.dmh+/+shNNMNNMMMMMMMNs-..``````````````````````.....----------::::-.:syhmNMMMMMNNh+..-:-:+o///+/..oddyo/--+dm"
"NNNNmdy+.``hNd+::+dNNNNMMMMMMMNd+-..```````````````````````.....-------------...:+osdNMMMMMMd-`.-/+s+o+soo/..+ddyo:.-+dm"
"NNNNmds/.``yNms:--hNNMMMMMMMMMNh+..``````````````````````````...------.......`...-/+odNMMMMMN/````...--+oo/..+ddyo/-./hm"
"NNNNNdy+-``sNNho/./NNNMMMMMMMNms:.````````````````````````````...----....````````.-::omNMMMMNo.`` ``-//++o+-.+ddhs/-.:ym"
"NNNNNdy+-``oNmh+/::mNMMMMMMMMNds:.````````````````````````````.........```    ````.--/hNMNmmNho-` `-+++sss+-.+ddhs/-.:ym"
"NNNNNdy+:``+Nh/..:+dNMMMMMMMMNds:.`````````````````````````````.......````       ``..-+hNNh+shso- `.:++syyo:./ddhs+-.-sm"
"NNNNNmho:` :NNmy+//hNMMMMMMMMNms:.``````````````````````````````.``.`.```````    ````.-+dNMNs+ds/``.ymmddhs:-/dmdy+-.-sm"
"NNNNNmho:` -NNmdo::hNMMMMMMMMNdo-.````````````` ```````````````````````........```  ``.-omMMMdsdo.://hdddhy/-+dmdyo:.-sN"
"NNNNNmho:` .mNmdo..oNNMMMMMMMNy:.````````````````````````````````````.-:+oshyyys/.`  ``.-hNMMmh:.`odoommdhy+-/hmdyo:.-om"
"NNNNNmho:. `dNmdy-`:mMMMMMMMMm+..``..:+so+++//:..`````````````````.-/ydmNNmmmmmdyo:.`  ``+hdmho.`-ydmdmmdhy+-/hmdho:..+m"
"NNNNNmho:. `yNmhy:-ymMMMmNMMMd:.``-ohhddmdmNNNNmdyo:.``````````..-+yyyyyssssyyyyys+:.    `::so-``-ydmmmmddho:/hmdho:../d"
"NNNNNmdo:.``sNmhs:-dNNNNNNMMNy.``.:+ooooyhhdmmNmdhyyo:.```````..-/+oyyyhNNMMNhdhyo/:-`    ``/o. `-sdmmmmmdyo:/hmmhs/..:h"
"NNNNNNds/-``+Nmho--mMNNNNMMNm+.```..--/shdsdNmNMy/++/:.``````..-+yysss/+NdNMs:yyo+/:-`      .-` `-ohdmmmmdyo//ymmhs/.`-h"
"NNNNNNds/.` :mmh+--mMNNNNNNmh-`````..-/++:-:hdmh:/o+-...````..-/sdhhdy+:+oso/:-.-..``       `.  `-ydmmmmmds+:/ymmds/.`-y"
"NNNNNNdy/.` -mmy+-:mMMNNNdNmo.``````.........--:://-...`````.--+yhhyso/:----::::-``         `` ` :ydmmmNmdy+:/smmdy/.`.s"
"NNNMNNmy+-` .mmy+:-dMMMMm:Nmo.```````````.....--::-...``````.-::osyyyys/:--::::-.``         `... -ydmmmmmmho//smmdy+.`.+"
"NNNNNNmh+-` `dmho-.hMMMMy.yms.`````````````.....-..`````````.-:::/+++++///:::::-..``         .-` -ydmmmmmmho//smmdh+-``/"
"NNNNNNmho-` `hmho-.hMMMNs.+ms-`````````````.....````````````.-:::::///:-:::-----..```           `:hmmmmmmdho::odmdh+-``-"
"NNNNMNmdo-```smho:.yMMMMs.+yho``````````````````````````````.-----:/::-------.......``       `  `:hmmmmmmdh+--+dmdho:``."
"NNNNMNmdo:```+mhs:.sMMMMN+.-yy:```````.`````````````````````.---..-+o:---....-.....```          `:hmmmmmmmy+--+dmdho:.`."
"NNNNNNNds/.` :mhs:.oMMMMMN-.+h+```````````````````...```````.--....:os:--..........```      `` `./hmmmmmmmh+--+dmmhs/.``"
"NNNNNNNdy+-` -dhs:.oMMMMMM:`/hs-`````````````````....````````.-.`...:s/--.......-..```      ```../dmmNNNmmho--+dmmds/-``"
"NNNNNNNdy+-` `hds:.+MMMMMMo`-oy+-````````````````...````.````...-://os/:---.....-...``      ./:../dmmmNmmmho-./hmmds+-``"
"MNNNNNmdy+.` `sds/./NMMMMMNo-oys+:```````````````````..:sy/-.-:ohNNmdhsso//---......``     .+o:..+dmmmmmmdy+-.:ymmdyo:.`"
"MNNNNNNdy+-`  +hs+-/NMMMMMNNmhhhy+-.```````````````.-:/smNmdddmNNMMMNNmdddhy+:---...```    .o+:.-smNNNNmmds/-.-sdmdy+-``"
"MNNNNNNmdo:`` :hs/.:NMMMMMMNmddmdo/:.````````...-://+yyhmmmNmmNNmmNMNNNmmmddhs/:----.-``   /hs/..sNNNNNNmdyo:-:ymmdy+-.`"
"MNNNNNNNds/.` .ys/.-mMMMMMMNmdhdmho/:..`````.:::oshsshssyyyyooyysosyyyysysoso+/::::/::.````.:yNmy+:+oshmNmmds/+dNNNmdy+:"
"MMNNNNNNmy+-` `ss+..mMMMMMMNNmhydmy++/-..```-/::+++++++///+oooooosssosyys+:::--:/+ooo:.``-o//ohMMMmy/.`.:/oso/odNNNNmmds"
"MNNNNNNNmho:` `oy+..dMMMMMMNNdy++sdy+++/-...--...-.-------::::::/++/////::::-//oyyhy+:.`.sNNNNNMMMMMNy:````.--:+ssydmdho"
"MNNNNNNNmds/.``+y+..hMMMMMMNmdy/:yNNhoo++:-----.````````..---::/::-------:::/sddmdyyo:.`+dNMMMMMMMMMMNd/````-/ss/.../oo/"
"MMNNNNNNmmyo-``/y+-.hMMMMMNmhsoymNNNmhhyo//+/+:..`````````.:osyhs/-...---:::+ymNNmmds-`-yhmNMMMMMMMMMMMm+````./syh+.````"
"MMNNNNNNmdho-` :y+-.yMMNmho//+mNMMMMN+ymdhss+:/o/:.```````.-:/oss+-...--::/+shmNNNNh/` /ysyNMMMMMMMMMMMMd/.``.:ooo+-.```"
"MMNNNNNNmds/.` -s+-.ohs++ohmmNMMMMMMM:-ymmhhhydmy:-``````..:/sosyso///+++oshmNMMMNmo:.`smsyMMMMMMMMMMMMMN+---.........``"
"MMNNNNMNmso+-` `+//+yhhdmNMMMMMMMMMMMo`./hNNNNNmy/::-..---:+/ooyysssyyhhhdmNNMMMNh+++:`dNhdMMMMMMMMMMMMMN/.....://:..``."
"MMMNNNNNNhso/.`-odNMMMMMMMMMMMMMMMMMMd.`.-ymNMMNmssys+++s+++sooyyyyyddmmNNNMMMNdsooss//MMNNMMMMMMMMMMMMMMNhysssyhds/.``."
"MMMNNNMNmh+::/yhmMMMMMMMMMMMMMMMMMMMMM/...-/ydmNMNmmmmdyhsssyhhhhyhdmmNNMMMMNNyosssys/hMMMMMMMMMMMMMMMMMMMMMNmmmNMmds/-."
"MMNNNmh+:-/hmNNNMMMMMMMMMMMMMMMMMMMMMMd-....--/ohdmNNMNNmdhhhdmmmmmmNMMMMNddhysssssysoMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMNmd"
"NNdyo/::::sNMMMMMMMMMMMMMMMMMMMMMMMMMMMo........-:/oydmNNNNNNNNNNNNNNNNNdsssssssssyysmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"///++osssshNMMMMMMMMMMMMMMMMMMMMMMMMMMMN/...........--:/+oyysssoossssooo+oossssssssydMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"oyhhddmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd:-.............``.......--:://++oooooo++osyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"ydmdmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh:-................``....-:/++++++o+++/+osdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"shmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy:-..................--::///++++o++///+shNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"sdNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo:-................---::///++oo+////+oydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd+:-................--:::/+++o+////+oshmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh+:-...............---:/+++++//::/+shddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+:---..........----::/+++///::/+oyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMds/:-.........---:://++++//::/+oyhdddMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdo/--......---::///++++/:::+oydmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMds/:--..--:://++++oo+///oydNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhs+///+oossyyyyyysooyhmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhhhhhdddddhhyysydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
;
}