// SPDX-License-Identifier: MIT
pragma solidity >=0.4.22 <0.9.0;

/**
Conceptuals are a collection of randomly generated conceptual metephors generated and
stored entirely on the Ethereum blockchain. These abstract thoughts and ideas can inspire
endless interpretations and use cases. Feel free to use Conceptuals in any way you see fit.

https://conceptualsproject.io
*/

/// [MIT License]
/// @title ConceptualsParts
/// @notice Concept parts for generating Conceptuals
/// @author Conceptuals Team <conceptualsproject.io>
library ConceptualsParts {
  function getPossessiveAdjectives() public pure returns (string[7] memory) {
    string[7] memory possessiveAdjectives = [
      "",
      "My",
      "Your",
      "His",
      "Her",
      "Its",
      "Our"
    ];

    return possessiveAdjectives;
  }

  function getLinkingVerbs() public pure returns (string[3] memory) {
    string[3] memory linkingVerbs = ["is", "are", "was"];

    return linkingVerbs;
  }

  function getArticles() public pure returns (string[3] memory) {
    string[3] memory articles = ["", "an", "a"];

    return articles;
  }

  function getTargetDomains() public pure returns (string[188] memory) {
    string[188] memory targetDomains = [
      "death",
      "generosity",
      "weakness",
      "hope",
      "honesty",
      "brilliance",
      "misery",
      "dedication",
      "trust",
      "bravery",
      "joy",
      "happiness",
      "sorrow",
      "wisdom",
      "fear",
      "humor",
      "intelligence",
      "humbleness",
      "stubbornness",
      "courageousness",
      "seriousness",
      "luckiness",
      "respect",
      "jealousy",
      "madness",
      "ambition",
      "rebellion",
      "compliance",
      "agreement",
      "desire",
      "grit",
      "optimism",
      "gratitude",
      "business",
      "health",
      "beauty",
      "wealth",
      "ferociousness",
      "daydreaming",
      "panic",
      "faith",
      "laziness",
      "pain",
      "glamour",
      "mystery",
      "literature",
      "secrets",
      "determination",
      "sadness",
      "excitement",
      "loneliness",
      "foolishness",
      "intrigue",
      "cruelty",
      "kindness",
      "greatness",
      "defeat",
      "hunger",
      "survival",
      "blindness",
      "empathy",
      "freedom",
      "resistance",
      "talent",
      "sympathy",
      "evil",
      "tolerance",
      "adventure",
      "confusion",
      "awareness",
      "anxiety",
      "pleasure",
      "failure",
      "envy",
      "heartache",
      "service",
      "chaos",
      "power",
      "warmth",
      "victory",
      "helplessness",
      "argument",
      "time",
      "labor",
      "war",
      "love",
      "existence",
      "structure",
      "admiration",
      "work",
      "tomorrow",
      "yesterday",
      "progress",
      "despair",
      "lust",
      "shame",
      "frustration",
      "pitty",
      "strength",
      "hatred"
      "control",
      "life",
      "heart",
      "equality",
      "racism",
      "air",
      "feminism",
      "calmness",
      "education",
      "rarity",
      "dominance",
      "resilience",
      "flexibility",
      "insanity",
      "hopelessness",
      "innocence",
      "cleanliness",
      "music",
      "art",
      "poetry",
      "revenge",
      "forgiveness",
      "energy",
      "kisses",
      "tears",
      "solutions",
      "eyes",
      "keys",
      "hands",
      "words",
      "claims",
      "ideas",
      "sounds",
      "answers",
      "questions",
      "men",
      "women",
      "people",
      "forests",
      "animals",
      "planets",
      "galaxies",
      "watches",
      "cities",
      "towns",
      "homes",
      "relationships",
      "children",
      "humans",
      "friends",
      "enemies",
      "adversaries",
      "wishes",
      "hopes",
      "dreams",
      "thoughts",
      "ambitions",
      "air",
      "end",
      "night",
      "morning",
      "day",
      "path",
      "road",
      "answer",
      "ocean",
      "answer",
      "solution",
      "start",
      "finish",
      "sun",
      "sky",
      "year",
      "month",
      "progress",
      "darkness",
      "foundation",
      "gate",
      "lesson",
      "memory",
      "antagonist",
      "rival",
      "goal",
      "journey",
      "sound",
      "dream",
      "mission",
      "hope",
      "design"
    ];

    return targetDomains;
  }

  function getSourceDomains() public pure returns (string[124] memory) {
    string[124] memory sourceDomains = [
      "heaven",
      "magic",
      "meaning",
      "forever",
      "sweet",
      "work",
      "insanity",
      "everything",
      "progress",
      "weakness",
      "strength",
      "money",
      "left",
      "armor",
      "bitter",
      "temporary",
      "death",
      "power",
      "war",
      "island",
      "enigma",
      "end",
      "angel",
      "arm",
      "answer",
      "riddle",
      "puzzle",
      "window",
      "mountain",
      "vehicle",
      "door",
      "table",
      "bed",
      "gift",
      "knife",
      "hammer",
      "candle",
      "bird",
      "raft",
      "book",
      "storm",
      "rock",
      "tornado",
      "wall",
      "hurdle",
      "vase",
      "gate",
      "house",
      "box",
      "prison",
      "road",
      "hill",
      "diamond",
      "hell",
      "horizon",
      "city",
      "friend",
      "weapon",
      "forest",
      "bridge",
      "dream",
      "myth",
      "day",
      "compass",
      "map",
      "man",
      "woman",
      "child",
      "lake",
      "universe",
      "dimension",
      "portal",
      "journey",
      "beginning",
      "law",
      "well",
      "reason",
      "destination",
      "place",
      "straight line",
      "windy road",
      "solution",
      "moment",
      "hug",
      "sunny day",
      "curse",
      "burden ",
      "ceiling",
      "light",
      "key",
      "garden",
      "river",
      "branch",
      "flower",
      "foundation",
      "forgiveness",
      "battlefield",
      "job",
      "structure",
      "buckle",
      "seed"
      "screen",
      "shop",
      "bank",
      "watch",
      "wave",
      "date",
      "ring",
      "letter",
      "reality",
      "mystery",
      "means",
      "kiss",
      "wish",
      "life",
      "tree",
      "ocean",
      "cure",
      "virus",
      "valley",
      "zoo",
      "godliness",
      "cancer",
      "sickness",
      "tomorrow"
    ];

    return sourceDomains;
  }
}

{
  "remappings": [],
  "optimizer": {
    "enabled": true,
    "runs": 200
  },
  "evmVersion": "istanbul",
  "libraries": {},
  "outputSelection": {
    "*": {
      "*": [
        "evm.bytecode",
        "evm.deployedBytecode",
        "abi"
      ]
    }
  }
}