/**
 *Submitted for verification at Etherscan.io on 2021-08-09
*/

/*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNNNmNNNNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNMmNdNyMNhmNMsMNmhNMyNdNmMNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNNmmmMhmMMdysMMMm:mMMMshdMMdhMmmmNNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNmdMNyNM+yMMMmmMMMhodMMMmNMMMs+MNhNMdmNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMmmmMhsyMMMNMy.:MMMMMs:sMMMMM:.hMNMMMsyhMmmmMMMMMMMMMMMMM
MMMMMMMMMMNmMNhNMMmhNMMMMNydMMMMMhydMMMMMhyNMMMMNymMMNhNNmNMMMMMMMMMM
MMMMMMMMMNmddN/dMMs`:MMNmNMMMMMMs` `sMMMMMMNmNMM:`sMMh/NddmNMMMMMMMMM
MMMMMMMNdhNMMMNMMMNmNMh.`.sMMMMMm+:+mMMMMMs``-dMNmMMMMNMMMNhdNMMMMMMM
MMMMMNNdMNosNsyMMMMMMMd-.-hMMMMMMMNMMMMMMMy-.:dMMMMMMNysNosNMdNNMMMMM
MMMMMNmyNMNNd:/NMMMMMMMNNNMMMMMmo--:omMMMMMNNNMMMMMMMN::mNNMNhmNMMMMM
MMMNmdmhsMMMMNNy/+yMMMMMNNMMMMM:    `/MMMMMNNMMMMMy//yNNMMMMshmdmNMMM
MMMNmNNmdNNMMMN.  -NMMh/--:sNMMo`  `.oMMNs:--/hMMN.  -NMMMNNdmNNmNMMM
MMNmhNNMm.-mMMMmyymMMm`   ``sMMMdsosdMMMs    `.mMMmyymMMMm.-mMNNhmNMM
MMmNNyoMMddMMMMMMMMMMN:   `-dMMMMMMMMMMMh.  ``/NMMMMMMMMMMddMM+hNNmMM
MNmhNMMMMMMMMNMMMMMMMMNhsshmMMMNmdhdmNMMMmyssdNMMMMMMMMNMMMMMMMMNhmNM
MmmmmdMmdNMh:-/mMMMNddmNMMMMMNs:.``.-:yNMMMMMNmddNMMMm/-:hMNdmMdmmmmM
MmmddsN:.hMo` .dMMs-``./dMMMM+`     ``.oMMMMd:.`.-yMMh` `sMy./MsddmmM
MmmmMMMmdNMNddmMMM`    `+MMMM`       ``-MMMM/    `-MMMmddMMNdmMMMmmmM
MmmmdsMMMMMMMMMMMMs.``./dMMMM+      ``.oMMMMd:```-yMMMMMMMMMMMMsdmmmM
MmmhmdMNdmMMMMMMMMMNddmNMMMMMNs-.```-/yNMMMMMNmddNMMMMMMMMMmmMMdmhmmM
MNdmMMMh.:NMm+/+mMMMMMNhssymMMMNmdhdmNMMMmyssdNMMMMMd+/oNMN-.hMMMmdNM
MMmdhhoNmmMMy` `sMMMMN:`  `-dMMMMMMMMMMMh.  ``/NMMMMo  `yMMmmN+hhdNMM
MMmmMmNMMMMMMhyhNMMMMm`   `.sMMMdsosdMMMs    `.mMMMMNhydMMMMMMNmMmmMM
MMMmmhMmdMmshMMMMMMMMMh:--:sNMMo`  `.oMMNo-.-/dMMMMMMMMMhsmMdmMhmmMMM
MMMNdNmysMy-+MMMMMNyshMMNNMMMMM:    `/MMMMMNNMNhsyNMMMMM/-hMshmNdNMMM
MMMMMmdNMMNNMMMMMM+  `hMMMMMMMMm+--:omMMMMMMMMy  `oMMMMMMNNMMNdmMMMMM
MMMMMNdNyNssMMMmymmo/sNMMMMMNNNMMMMMMMNNNMMMMMNo/ommymMMMosNyNdNMMMMM
MMMMMMMmmNdNMMNo.+MMMMMMMMMy.`-dMMMMMd-`-yMMMMMMMMM/.sNMMNdNmmMMMMMMM
MMMMMMMMMmdNMN/dMMMMMMNNMMMy.`-dMMMMMh.`.yMMMNNMMMMMMh/NMNdmMMMMMMMMM
MMMMMMMMMMNNdhMMMMmmMm..dMMMNmNMMMMMMMNmNMMMd`.mMmmMMMMhdNNMMMMMMMMMM
MMMMMMMMMMMMMNdmdMssMMmdMMMMMo.+MMMMM+.sMMMMNdmMMsyMdmdNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNmNddMMN+yMMMmhymMMNMMmyhNMMMy+NMMddNmNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNMNmNsMMyNMysMMMm:mMMMoyMNyMMsNmNMNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNMNdNdNhhNNymMmhNNhdNdNdNMNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNNmNmMNNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
*/
pragma solidity ^0.4.23;
contract compusophyLogo {}