/**
 *Submitted for verification at Etherscan.io on 2021-09-15
*/

pragma solidity ^0.8.0;
library LOOKLib {

    function textures() public pure returns (string[64] memory) {
        return
        [
        "Silky",
        "Velvety",
        "Slimy",
        "Sharp",
        "Latex",
        "Wool",
        "Scaly",
        "Coarse",
        "Sandy",
        "Rocky",
        "Bumpy",
        "Slippery",
        "Fuzzy",
        "Synthetic",
        "Rough",
        "Fizzy",
        "Sticky",
        "Slick",
        "Popcorn",
        "Cotton Candy",
        "Slap Brush",
        "Feathery",
        "Prickly",
        "Crows Feet",
        "Smooth",
        "Cloudy",
        "Misty",
        "Bristly",
        "Solid",
        "Liquid",
        "Foamy",
        "Spongey",
        "Gelatinous",
        "Crumbly",
        "Spiked",
        "Crackled",
        "Barbed",
        "Crusty",
        "Powdery",
        "Leathery",
        "Squishy",
        "Wrinkly",
        "Reflective",
        "Glittery",
        "Felt",
        "Puffy",
        "Fleece",
        "Polymer",
        "Ceramic",
        "Chiffon",
        "Plastic",
        "Glass",
        "Lumpy",
        "Cotton",
        "Denim",
        "Lace",
        "Double Knit",
        "Knit",
        "Lace",
        "Mesh",
        "Nylon",
        "Satin",
        "Tactel",
        "Wool"
        ];

    }

    function flares() public pure returns (string[45] memory) {
        return
        [
        "Empty Wine Bottle",
        "Copper Dragon",
        "Sugary Cereal",
        "White Dragon",
        "Rainbow Serpent",
        "Paradise A Burn",
        "Asteroid En Route",
        "Neptune Sword",
        "Jupiter Honey",
        "Cosmic Heat",
        "Indie Luna",
        "Flashbulb Camera",
        "Category Four Hurricane",
        "Blood Mustang",
        "Candle in the Wind",
        "Diamond Wave",
        "All Powerful Trident",
        "Multifaceted Buzz",
        "1964 California Spyder",
        "Millions of Polka Dots",
        "Interstellar Mass",
        "Endless Galaxies",
        "A 1999 Video Game",
        "Glimmering Swimming Pool",
        "Black Cristal",
        "Zero Gravity",
        "Coney Island",
        "Aerodynamic Steering Wheel",
        "National Turbulence",
        "Heavy Metal Hour",
        "Seagull\xE2\x80\x99s Circling",
        "Mermaid Motel",
        "Self Loathing Poet",
        "Canyon\xE2\x80\x99s Infinite Abyss",
        "Diet Mountain Dew",
        "Harem Silks From Bombay",
        "Rolling Party Ashes",
        "Gate of the Gargoyles",
        "Bel Air Palm Trees",
        "Rare Jazz Collection",
        "Hydroponic Weed",
        "Spicy Caviar",
        "Brooklyn Cola Bottle",
        "Wabi Sabi",
        "Summer Apartment Complex"
        ];
    }

    function colours() public pure returns (string[54] memory) {
        return [
        "Crow Black",
        "Raven Black",
        "Jet Black",
        "Black as Night",
        "Black as Ink",
        "Milky White",
        "Pearl White",
        "Sugar White",
        "Eggshell White",
        "Scarlet",
        "Crimson",
        "Ruby Red",
        "Cranberry",
        "Aqua",
        "Navy",
        "Turquoise",
        "Teal",
        "Aquamarine",
        "Golden Oak",
        "Sapphire Blue",
        "Glacial Blue",
        "Lemon Yellow",
        "Butter Yellow",
        "Military Green",
        "Sunshine Yellow",
        "Golden Blue",
        "Silver Red",
        "Silver Purple",
        "Golden Purple",
        "Golden Green",
        "Golden Orange",
        "Silver Teal",
        "Jade",
        "Lime Green",
        "Bottle Green",
        "Flamingo Pink",
        "Shell Pink",
        "Violet",
        "Pansy Purple",
        "Pumpkin Orange",
        "Sunset Orange",
        "Tiger Lily Orange",
        "Mocha Brown",
        "Coffee Brown",
        "Bronze Green",
        "Cinnamon Yellow",
        "Caramel Orange",
        "Burnt Red",
        "Caramel Yellow",
        "Hazel Gray",
        "Charcoal Gray",
        "Mellow Yellow",
        "Smoke Gray",
        "Cocoa Brown"
        ];
    }

    function backgroundColours() public pure returns (string[30] memory) {
        return [
        "FF0294",
        "02FF6A",
        "EE740D",
        "EE0D0D",
        "00C0D0",
        "0056F6",
        "C600F6",
        "F60091",
        "CA215C",
        "DA9708",
        "5EDA08",
        "DA801A",
        "771ADA",
        "1A6EDA",
        "1AC6DA",
        "18B144",
        "7E18B1",
        "A533DE",
        "A8DE33",
        "D9DE33",
        "DE7C33",
        "E36100",
        "E300BA",
        "731F64",
        "66D83F",
        "3FB5D8",
        "000000",
        "3B289B",
        "9B285E",
        "3ACFA4"
        ];
    }

    function lines() public pure returns (string[41] memory) {
        return [
        "Angular",
        "Fringe",
        "Quiff",
        "Pegged",
        "Blouson",
        "Halter",
        "Bouffant",
        "Tunic",
        "Chemise",
        "Balloon",
        "Bretelles",
        "Embroidery",
        "Drop Waist",
        "Peplum",
        "Bowl Cut",
        "Jagged",
        "Drape",
        "Princess Line",
        "Yolk Line",
        "Crossover Line",
        "Chain stitch",
        "Hand Stitch",
        "Lock Stitch",
        "Gimp",
        "Multi-Thread Stitch",
        "Over Edge Stitch",
        "Blanket Stitch",
        "Running Stitch",
        "Satin Stitch",
        "French Knot Stitch",
        "Lazy Daisy Stitch",
        "Herringbone Stitch",
        "Seed Stitch",
        "Bullion Knot",
        "Buttonhole Stitch",
        "Shell Tuck Stitch",
        "Square Knot",
        "Water Knot",
        "Rolling Hitch",
        "Blood Knot",
        "Tripod Lashing"
        ];
    }

    function shapes() public pure returns (string[41] memory) {
        return [
        "Spiral",
        "Maxi",
        "Empire",
        "Asymmetrical",
        "A-line",
        "Sheath",
        "Hourglass",
        "Bell",
        "Mermaid",
        "Ball",
        "Trumpet",
        "Squiggle",
        "Ruffle",
        "Lemniscate",
        "Mobius Strip",
        "Squircle",
        "Heptagram",
        "Butterfly Curve",
        "Inverted Bell",
        "Golden Ratio",
        "Cos",
        "Sine",
        "S Curve",
        "Deltoid",
        "Cassini Oval",
        "Spline",
        "B\xC3\xA9zier triangle",
        "Roulette",
        "Cone",
        "Torus",
        "Honeycomb",
        "Star",
        "Broken",
        "Obtuse",
        "Straight",
        "Wavy",
        "Diagonal",
        "Prism",
        "Ring",
        "ZigZag",
        "Mangled"
        ];
    }

    function forms() public pure returns (string[23] memory) {
        return [
        "Antifragile",
        "Fragile",
        "Shifting",
        "Temporal",
        "Terrestrial",
        "Ephemeral",
        "Transient",
        "Intense",
        "Flimsy",
        "Reliable",
        "Fading",
        "Bright",
        "Repaired",
        "Renewed",
        "Over Extended",
        "Retracted",
        "Halted",
        "Short Form",
        "Long Form",
        "Kintsugi",
        "Downforce",
        "Melting",
        "Quenched"
        ];
    }

    function elements() public pure returns (string[113] memory) {
        return [
        "Hydrogen",
        "Helium",
        "Lithium",
        "Beryllium",
        "Boron",
        "Carbon",
        "Nitrogen",
        "Oxygen",
        "Fluorine",
        "Neon",
        "Sodium",
        "Magnesium",
        "Aluminum",
        "Silicon",
        "Phosphorus",
        "Sulfur",
        "Chlorine",
        "Argon",
        "Potassium",
        "Calcium",
        "Scandium",
        "Titanium",
        "Vanadium",
        "Chromium",
        "Manganese",
        "Iron",
        "Cobalt",
        "Nickel",
        "Copper",
        "Zinc",
        "Gallium",
        "Germanium",
        "Arsenic",
        "Selenium",
        "Bromine",
        "Krypton",
        "Rubidium",
        "Strontium",
        "Yttrium",
        "Zirconium",
        "Niobium",
        "Molybdenum",
        "Technetium",
        "Ruthenium",
        "Rhodium",
        "Palladium",
        "Silver",
        "Cadmium",
        "Indium",
        "Tin",
        "Antimony",
        "Tellurium",
        "Iodine",
        "Xenon",
        "Cesium",
        "Barium",
        "Lanthanum",
        "Cerium",
        "Praseodymium",
        "Neodymium",
        "Promethium",
        "Samarium",
        "Europium",
        "Gadolinium",
        "Terbium",
        "Dysprosium",
        "Holmium",
        "Erbium",
        "Thulium",
        "Ytterbium",
        "Lutetium",
        "Hafnium",
        "Tantalum",
        "Tungsten",
        "Rhenium",
        "Osmium",
        "Iridium",
        "Platinum",
        "Gold",
        "Mercury",
        "Thallium",
        "Lead",
        "Bismuth",
        "Polonium",
        "Astatine",
        "Radon",
        "Francium",
        "Radium",
        "Actinium",
        "Thorium",
        "Protactinium",
        "Uranium",
        "Neptunium",
        "Plutonium",
        "Americium",
        "Curium",
        "Berkelium",
        "Californium",
        "Einsteinium",
        "Fermium",
        "Mendelevium",
        "Nobelium",
        "Lawrencium",
        "Rutherfordium",
        "Dubnium",
        "Seaborgium",
        "Bohrium",
        "Hassium",
        "Meitnerium",
        "Darmstadtium",
        "Roentgenium",
        "Ununbiium",
        "Ununquadium"
        ];
    }
}