// SPDX-License-Identifier: Unlicensed
// A Creative Commons license will be here later

pragma solidity ^0.8.0;

interface TraitDB {
  function viewTrait(uint256 _id) external view returns (string memory);
  function totalTraits() external view returns (uint256);
}

contract AttrPockets is TraitDB {
  string[] internal pockets = [
  "Dirt"
  , "Sand"
  , "Cotton ball"
  , "Pebble"
  , "Fork"
  , "Butter knife"
  , "Spoon"
  , "Fingernail"
  , "Toenail"
  , "Lint"
  , "Wood shavings"
  , "Apple core"
  , "Nuts"
  , "Moonshine"
  , "Ale"
  , "Waterskin "
  , "Wineskin"
  , "Pottery shards"
  , "Barley"
  , "Coal"
  , "Bento box (empty)"
  , "Prophylactic (used)"
  , "Prophylactic (new) "
  , "Birdseed"
  , "Packet of salt "
  , "Hand knitted scarf"
  , "Tuft of fur"
  , "Hairball"
  , "Triangle (musical instrument)"
  , "Checkers set"
  , "Blank scroll"
  , "Quill and ink"
  , "Sea glass"
  , "Seaweed"
  , "Good Luck Rock (magical item)"
  , "Pearl of Power"
  , "Vial (truth serum - 1 use) "
  , "Vial (viper poison - 1 use)"
  , "Vial (pufferfish poison - 1 use) "
  , "Vial (good luck draught - 1 use)"
  , "Vial (healing potion - 1 use)"
  , "1 strand unicorn hair"
  , "Vial (chutney - 1 use)"
  , "Bezoar"
  , "Magical parchment"
  , "Vial (empty)"
  , "Egg (rotten)"
  , "Egg (raw)"
  , "Rusted coin"
  , "Jar ('dragonbreath')"
  , "Magic perfume"
  , "Magic cologne"
  , "Wizard's honor badge"
  , "Hypnosis necklace"
  , "Pamphlet ('Guide to the Cataclysm')"
  , "Pamphlet ('Guide to the Apocalypse')"
  , "Pamphlet ('Guide to Damnation')"
  , "Pamphlet ('Guide to Pandemonium')"
  , "Pamphlet ('Guide to the Divine')"
  , "Pamphlet ('Guide to the Twins')"
  , "Crumpled note"
  , "Abacus"
  , "Magical abacus (calculates on voice command)"
  , "Manual ('Destoning golems')"
  , "Manual ('Disassembling chimeras')"
  , "Manual ('Antidotes to viper poison')"
  , "Manual ('Standing on giants' shoulders')"
  , "Manual ('Disarming krakens')"
  , "Manual ('Dowsing phoenix flame')"
  , "Manual ('Beautifying ogres')"
  , "Manual ('Socializing trolls')"
  , "Manual ('Friend-zoning ghosts')"
  , "Pamphlet ('Guide to the Holy')"
  , "Manual ('Tinder for soulmating')"
  , "Manual ('How to wear bees')"
  , "Manual ('How to breathe fire')"
  , "Pamphlet ('Guide to the Titans')"
  , "Manual ('How to breathe underwater')"
  , "Pamphlet ('Guide to the Plague')"
  , "Manual ('How to speak to plague deniers')"
  , "Manual ('So your son is into necromancy...')"
  , "Nail"
  , "Lumber"
  , "Bricks"
  , "Slab of stone"
  , "Miniature bridge of hair"
  , "Orb of Firestarting (5 uses)"
  , "Orb of Black Light (5 uses)"
  , "Orb of White Light (5 uses)"
  , "Ground flaxseed"
  , "Ground coffee beans"
  , "Loose tea leaves"
  , "Gordian knot"
  , "Miniature bored ape"
  , "Miniature moon cat"
  , "Miniature pengu"
  , "Miniature cryptic punk"
  , "Pamphlet ('Guide to Loot (for Adventurers)')"
  , "Miniature cryptic kitten"
  , "Sixty-sided die"
  , "Mutation serum"
  , "Miniature degenerate ape"
  , "Turnips"
  , "Cursed relic"
  , "Cracked goblet"
  , "False jewel"
  , "False coin"
  , "Piece of the True Cross"
  , "Capon"
  , "Sack wine"
  , "Dice"
  , "Seal-ring worth forty mark"
  , "Chitterlings"
  , "Rose petals"
  , "Wet socks"
  , "Star chart"
  , "Wooden beetle"
  , "Marionette"
  , "Book of sonnets"
  , "Miniature rock of Sisyphus"
  , "Dungeon keys"
  , "Graveyard dirt"
  , "Sky stone"
  , "Jackknife"
  , "Sail needle"
  , "Scrimshawed whale tooth"
  , "Scrimshawed walrus tusk"
  , "A list of letters in the alphabet"
  , "Manual ('So your life is runed...')"
  , "More pockets"
  , "Drawing of first love"
  , "Drawing of mortal enemy"
  , "Locket"
  , "Ore (copper)"
  , "Ore (iron)"
  , "Fishing rod"
  , "Book (romance)"
  , "Book (adventure)"
  , "Book (history)"
  , "Book (governance)"
  , "Book (accounting)"
  , "Sex swing"
  , "Ball of wax"
  , "Sewing kit"
  , "Bandage"
  , "Baker's yeast"
  , "Brewer's yeast"
  , "Jar (honey)"
  , "Love letter"
  , "Sugar"
  , "Poison"
  , "Holy relic"
  , "Toadstool"
  , "Monkey's paw (used)"
  , "Sparrow"
  , "Magic beans"
  , "Treasure map"
  , "Harp"
  , "Jar (elvers)"
  , "Chess set"
  , "Chewing tobacco"
  , "Sleeping draught"
  , "Small bag of silver coins"
  , "Blood (bear)"
  , "Scat (bear)"
  , "Essence (bear)"
  , "Eye (bear)"
  , "Hide (bear)"
  , "Nail (bear)"
  , "Teeth (bear)"
  , "Blood (boar)"
  , "Scat (boar)"
  , "Essence (boar)"
  , "Eye (boar)"
  , "Hide (boar)"
  , "Teeth (boar)"
  , "Blood (crow)"
  , "Scat (crow)"
  , "Egg (crow)"
  , "Essence (crow)"
  , "Eye (crow)"
  , "Feather (crow)"
  , "Wings (crow)"
  , "Scat (dragonfly)"
  , "Essence (dragonfly)"
  , "Wings (dragonfly)"
  , "Blood (squid)"
  , "Scat (squid)"
  , "Essence (squid)"
  , "Eye (squid)"
  , "Blood (spider)"
  , "Scat (spider)"
  , "Egg (spider)"
  , "Essence (spider)"
  , "Eye (spider)"
  , "Blood (owl)"
  , "Scat (owl)"
  , "Egg (owl)"
  , "Essence (owl)"
  , "Eye (owl)"
  , "Feather (owl)"
  , "Blood (vulture)"
  , "Scat (vulture)"
  , "Essence (vulture)"
  , "Eye (vulture)"
  , "Feather (vulture)"
  , "Nail (vulture)"
  , "Blood (swan)"
  , "Scat (swan)"
  , "Egg (swan)"
  , "Essence (swan)"
  , "Eye (swan)"
  , "Feather (swan)"
  , "Teeth (swan)"
  , "Roast chicken"
  , "Cooked rabbit"
  , "Skin (chicken)"
  , "Blood (wolf)"
  , "Scat (wolf)"
  , "Essence (wolf)"
  , "Eye (wolf)"
  , "Hide (wolf)"
  , "Nail (wolf)"
  , "Teeth (wolf)"
  , "Blood (tortoise)"
  , "Scat (tortoise)"
  , "Egg (tortoise)"
  , "Essence (tortoise)"
  , "Eye (tortoise)"
  , "Shell (tortoise)"
  , "Teeth (tortoise)"
  , "Scat (worm)"
  , "Essence (worm)"
  , "Skin (worm)"
  , "Blood (raven)"
  , "Scat (raven)"
  , "Egg (raven)"
  , "Essence (raven)"
  , "Eye (raven)"
  , "Feather (raven)"
  , "Teeth (raven)"
  , "Blood (snake)"
  , "Scat (snake)"
  , "Egg (snake)"
  , "Essence (snake)"
  , "Eye (snake)"
  , "Skin (snake)"
  , "Scat (bees)"
  , "Essence (bees)"
  , "Hide (bees)"
  , "Wings (bees)"
  , "Blood (goat)"
  , "Scat (goat)"
  , "Essence (goat)"
  , "Eye (goat)"
  , "Fur (goat)"
  , "Hide (goat)"
  , "Teeth (goat)"
  , "Blood (newt)"
  , "Scat (newt)"
  , "Essence (newt)"
  , "Eye (newt)"
  , "Skin (newt)"
  , "Teeth (newt)"
  , "Lichen"
  , "Orb of Good Advice "
  , "Jar of Gaseous Gust "
  , "Vial (Elixir of confusion - 1 use)"
  , "Gum"
  , "Eye (pike)"
  , "Scale (pike)"
  , "Egg (pike)"
  , "Essence (pike)"
  , "Scale (cod)"
  , "Egg (cod)"
  , "Essence (cod)"
  , "Scale (char)"
  , "Egg (char)"
  , "Essence (char)"
  , "Scale (trout)"
  , "Egg (trout)"
  , "Essence (trout)"
  , "Scale (carp)"
  , "Egg (carp)"
  , "Essence (carp)"
  , "Eye (char)"
  , "Eye (cod)"
  , "Eye (trout)"
  , "Eye (carp)"
  , "Eye (eel)"
  , "Scale (catfish)"
  , "Egg (catfish)"
  , "Essence (catfish)"
  , "Teeth (eel)"
  , "Skin (eel)"
  , "Egg (eel)"
  , "Essence (eel)"
  , "Six-sided Instrument of Prediction"
  , "Hole of Never-Ending Depth"
  , "Banknotes"
  , "Ticket to the fair"
  , "Serrated blade"
  , "Wine key"
  , "Phoenix egg"
  , "Perspective glass"
  , "Spring clock"
  , "Rejuvenating berries"
  , "Pirate flag"
  , "Basilisk fang"
  , "Incantation scrawled on tavern napkin"
  , "Contract scrawled on tavern napkin"
  , "Illegible scrip"
  , "Ruby reagent"
  , "Emerald reagent"
  , "Diamond reagent"
  , "Sapphire reagent"
  , "Rainbow reagent"
  , "Gem pouch"
  , "Potion pouch"
  , "Coin pouch"
  , "Pouch extension"
  , "Stirrups"
  , "Blinders"
  , "Saddle"
  , "Royal saddle"
  , "Royal blinders"
  , "Royal stirrups"
  , "Manual ('Putting the 'care' in apothecary')"
  , "Anklecuffs"
  , "Silk binding"
  , "Brightsilk binding"
  , "Leather binding"
  , "Ball gag"
  , "Gimp mask"
  , "Key to Maison de Plaisir"
  , "Key to Mourner's Lodge"
  , "Key to Cottage of the Great Bard"
  , "Pamphlet ('Join the Tiny Bigg Shim Coconut Circus today!')"
  , "Key to Tiny's Circus Tent"
  , "Key to Bigg's Circus Tent"
  , "Key to Shim's Circus Tent"
  , "Key to Coconut's Circus Tent"
  , "Whale bone"
  , "Ticklejuice"
  , "Egg (robin)"
  , "Gold ring"
  , "Ruby amulet"
  , "Magic wand"
  , "Ore (silver)"
  , "Book (war strategy)"
  , "Book (wizardry)"
  , "Poultice"
  , "Crabs"
  , "Dowsing rods"
  , "Ostracon"
  , "Melted ice"
  , "Fairy dust"
  , "Willowsap"
  , "Amber spyglass"
  , "Cursed talking doll"
  , "Sapphire diadem"
  , "Lockpick kit"
  , "Bats"
  , "Flask of healing potion"
  , "Guitar"
  , "Lyre"
  , "Sandsnake"
  , "Ghost crab"
  , "Vial (viper poison - 5 uses)"
  , "Vial (pufferfish poison - 5 uses) "
  , "Vial (good luck draught - 5 uses)"
  , "Vial (chutney - 5 uses)"
  , "Small bag of gold coins "
  , "Six talents"
  , "A single guilder"
  , "Seven drachma"
  , "Book (law)"
  , "Singing cricket"
  , "Almagest"
  , "Tycho's Nose"
  , "De rerum natura"
  , "Blood (ogre)"
  , "Scat (ogre)"
  , "Essence (ogre)"
  , "Eye (ogre)"
  , "Nail (ogre)"
  , "Skin (ogre)"
  , "Teeth (ogre)"
  , "Blood (pixie)"
  , "Scat (pixie)"
  , "Essence (pixie)"
  , "Wings (pixie)"
  , "Blood (troll)"
  , "Scat (troll)"
  , "Essence (troll)"
  , "Eye (troll)"
  , "Nail (troll)"
  , "Skin (troll)"
  , "Teeth (troll)"
  , "Blood (yeti)"
  , "Scat (yeti)"
  , "Essence (yeti)"
  , "Eye (yeti)"
  , "Fur (yeti)"
  , "Nail (yeti)"
  , "Skin (yeti)"
  , "Teeth (yeti)"
  , "Blood (lion)"
  , "Scat (lion)"
  , "Essence (lion)"
  , "Eye (lion)"
  , "Fur (lion)"
  , "Hide (lion)"
  , "Nail (lion)"
  , "Teeth (lion)"
  , "Blood (halfling)"
  , "Scat (halfling)"
  , "Essence (halfling)"
  , "Eye (halfling)"
  , "Nail (halfling)"
  , "Skin (halfling)"
  , "Teeth (halfling)"
  , "Blood (porpoise)"
  , "Scat (porpoise)"
  , "Essence (porpoise)"
  , "Eye (porpoise)"
  , "Nail (porpoise)"
  , "Skin (porpoise)"
  , "Teeth (porpoise)"
  , "Blood (shark)"
  , "Scat (shark)"
  , "Essence (shark)"
  , "Eye (shark)"
  , "Hide (shark)"
  , "Teeth (shark)"
  , "Rock-tripe"
  , "Graphic novel"
  , "Eye (hobthrush)"
  , "Eye (weedy seadragon)"
  , "Eye (stargazer)"
  , "Eye (babel fish)"
  , "Scale (snakehead)"
  , "Egg (snakehead)"
  , "Essence (snakehead)"
  , "Scale (burbot)"
  , "Egg (burbot)"
  , "Essence (burbot)"
  , "Claw (crawdad)"
  , "Essence (kelpy)"
  , "Egg (crawdad)"
  , "Essence (crawdad)"
  , "Scale (weedy seadragon)"
  , "Egg (weedy seadragon)"
  , "Essence (weedy seadragon)"
  , "Scale (stargazer)"
  , "Egg (stargazer)"
  , "Essence (stargazer)"
  , "Scale (babel fish)"
  , "Egg (babel fish)"
  , "Essence (babel fish)"
  , "Scale (arowana)"
  , "Egg (arowana)"
  , "Essence (arowana)"
  , "Hide (manticore)"
  , "Essence (manticore)"
  , "Scat (manticore)"
  , "Scale (hobthrush)"
  , "Egg (hobthrush)"
  , "Essence (hobthrush)"
  , "Eye (snakehead)"
  , "Eye (catfish)"
  , "Eye (burbot)"
  , "Eye (kelpy)"
  , "Eye (crawdad)"
  , "Eye (arowana)"
  , "Rare drawing of humanoid frog"
  , "Four Inch Tungsten Cube"
  , "Eight Inch Tungsten Cube"
  , "Impossibly-dense Cube (not Tungsten)"
  , "Silver lining"
  , "Rock of Crushing (roshambo)"
  , "Scissors of Shredding (roshambo)"
  , "Paper of Smothering (roshambo)"
  , "Broken Palantir"
  , "Palantir"
  , "Letter to the editor"
  , "Mashed potatoes"
  , "Sliced steak"
  , "Dragontooth"
  , "Ore (gold)"
  , "Ruby"
  , "Emerald"
  , "Sapphire"
  , "Book (poetry)"
  , "Book (epic tale)"
  , "Amber"
  , "Monkey's paw (unused) "
  , "Merkin (red)"
  , "Merkin (brown)"
  , "Electric guitar"
  , "Book (alchemy)"
  , "Seer stone"
  , "Egg (buzzard)"
  , "Oracle bone"
  , "Ring of Cock"
  , "Egg (eagle)"
  , "Silver flute"
  , "Bloodworm"
  , "Universal translator"
  , "Pouch of gold and silver coins "
  , "Jar (Number One Sons Pickles)"
  , "Vial (truth serum - 7 uses)"
  , "Flightless worm"
  , "Book (holy)"
  , "Book (unholy)"
  , "Book (cursed)"
  , "Book (hexed)"
  , "Blood (basilisk)"
  , "Scat (basilisk)"
  , "Egg (basilisk)"
  , "Essence (basilisk)"
  , "Eye (basilisk)"
  , "Scale (basilisk)"
  , "Blood (centaur)"
  , "Scat (centaur)"
  , "Essence (centaur)"
  , "Eye (centaur)"
  , "Hide (centaur)"
  , "Teeth (centaur)"
  , "Blood (chimera)"
  , "Scat (chimera)"
  , "Essence (chimera)"
  , "Eye (chimera)"
  , "Hide (chimera)"
  , "Teeth (chimera)"
  , "Blood (cyclops)"
  , "Scat (cyclops)"
  , "Essence (cyclops)"
  , "Eye (cyclops)"
  , "Nail (cyclops)"
  , "Skin (cyclops)"
  , "Teeth (cyclops)"
  , "Blood (demon)"
  , "Scat (demon)"
  , "Egg (demon)"
  , "Essence (demon)"
  , "Eye (demon)"
  , "Hide (demon)"
  , "Horn (demon)"
  , "Nail (demon)"
  , "Teeth (demon)"
  , "Blood (elf)"
  , "Scat (elf)"
  , "Essence (elf)"
  , "Eye (elf)"
  , "Nail (elf)"
  , "Skin (elf)"
  , "Teeth (elf)"
  , "Blood (mermaid)"
  , "Scat (mermaid)"
  , "Essence (mermaid)"
  , "Eye (mermaid)"
  , "Fin (mermaid)"
  , "Nail (mermaid)"
  , "Scale (mermaid)"
  , "Teeth (mermaid)"
  , "Blood (gnome)"
  , "Scat (gnome)"
  , "Essence (gnome)"
  , "Eye (gnome)"
  , "Nail (gnome)"
  , "Skin (gnome)"
  , "Teeth (gnome)"
  , "Blood (giant)"
  , "Scat (giant)"
  , "Essence (giant)"
  , "Eye (giant)"
  , "Nail (giant)"
  , "Skin (giant)"
  , "Teeth (giant)"
  , "Blood (narwhal)"
  , "Scat (narwhal)"
  , "Essence (narwhal)"
  , "Eye (narwhal)"
  , "Skin (narwhal)"
  , "Blood (siren)"
  , "Scat (siren)"
  , "Essence (siren)"
  , "Eye (siren)"
  , "Skin (siren)"
  , "Teeth (siren)"
  , "Blood (werewolf)"
  , "Scat (werewolf)"
  , "Essence (werewolf)"
  , "Eye (werewolf)"
  , "Hide (werewolf)"
  , "Nail (werewolf)"
  , "Teeth (werewolf)"
  , "Teeth (rooster)"
  , "Jar (moonlight)"
  , "Wizardbeard"
  , "Eye (elephant)"
  , "Eye (peacock)"
  , "Eye (manticore)"
  , "Teeth (manticore)"
  , "Nail (manticore)"
  , "Blood (manticore)"
  , "Teeth (elephant)"
  , "Blood (elephant)"
  , "Essence (axolotl)"
  , "Essence (alzabo)"
  , "Hide (alzabo)"
  , "Hide (elephant)"
  , "Essence (elephant)"
  , "Scat (elephant)"
  , "Blood (peacock)"
  , "Heart (peacock)"
  , "Feather (peacock)"
  , "Egg (peacock)"
  , "Essence (peacock)"
  , "Scat (peacock)"
  , "Ore (mithril)"
  , "Gilded spoon"
  , "Gilded fork"
  , "Gilded knife"
  , "Royal spoon"
  , "Royal fork"
  , "Royal knife"
  , "Silver spoon"
  , "Silver fork"
  , "Silver knife"
  , "Invisibility cloak"
  , "Diamond"
  , "Scorpion necklace"
  , "Scorpion key"
  , "White orb"
  , "Black orb"
  , "Book (necromancy)"
  , "Book (witchcraft)"
  , "Book (summoning)"
  , "Grimoire"
  , "Necronomicon"
  , "Philosopher's Stone"
  , "Urim and Thummim"
  , "Teonanacatl"
  , "Moonbeam"
  , "Bottle (lightning)"
  , "Cursed ruby tiara"
  , "Cursed emerald tiara "
  , "Cursed diamond tiara"
  , "Spiss fleinsopp"
  , "Antler of Adumbration"
  , "Endless bag of gold and silver coins "
  , "Ore (readilyobtainium)"
  , "Bagel"
  , "Blood (Bigfoot)"
  , "Scat (Bigfoot)"
  , "Essence (Bigfoot)"
  , "Eye (Bigfoot)"
  , "Hide (Bigfoot)"
  , "Nail (Bigfoot)"
  , "Teeth (Bigfoot)"
  , "Blood (dragon)"
  , "Scat (dragon)"
  , "Egg (dragon)"
  , "Essence (dragon)"
  , "Eye (dragon)"
  , "Hide (dragon)"
  , "Horn (dragon)"
  , "Nail (dragon)"
  , "Scale (dragon)"
  , "Teeth (dragon)"
  , "Blood (fairy)"
  , "Scat (fairy)"
  , "Essence (fairy)"
  , "Eye (fairy)"
  , "Nail (fairy)"
  , "Teeth (fairy)"
  , "Wings (fairy)"
  , "Blood (leprechaun)"
  , "Scat (leprechaun)"
  , "Essence (leprechaun)"
  , "Eye (leprechaun)"
  , "Nail (leprechaun)"
  , "Skin (leprechaun)"
  , "Teeth (leprechaun)"
  , "Blood (lynx)"
  , "Scat (lynx)"
  , "Essence (lynx)"
  , "Eye (lynx)"
  , "Hide (lynx)"
  , "Nail (lynx)"
  , "Teeth (lynx)"
  , "Scat (mandrake)"
  , "Essence (mandrake)"
  , "Blood (Medusa)"
  , "Scat (Medusa)"
  , "Essence (Medusa)"
  , "Eye (Medusa)"
  , "Skin (Medusa)"
  , "Blood (kraken)"
  , "Scat (kraken)"
  , "Egg (kraken)"
  , "Essence (kraken)"
  , "Eye (kraken)"
  , "Scale (kraken)"
  , "Blood (hydra)"
  , "Scat (hydra)"
  , "Egg (hydra)"
  , "Essence (hydra)"
  , "Eye (hydra)"
  , "Scale (hydra)"
  , "Blood (griffin)"
  , "Scat (griffin)"
  , "Essence (griffin)"
  , "Eye (griffin)"
  , "Hide (griffin)"
  , "Nail (griffin)"
  , "Teeth (griffin)"
  , "Blood (Minotaur)"
  , "Scat (Minotaur)"
  , "Essence (Minotaur)"
  , "Eye (Minotaur)"
  , "Hide (Minotaur)"
  , "Blood (Pegasus)"
  , "Scat (Pegasus)"
  , "Essence (Pegasus)"
  , "Eye (Pegasus)"
  , "Feather (pegasus)"
  , "Teeth (Pegasus)"
  , "Blood (phoenix)"
  , "Scat (phoenix)"
  , "Egg (phoenix)"
  , "Essence (phoenix)"
  , "Eye (phoenix)"
  , "Feather (phoenix)"
  , "Blood (sphinx)"
  , "Scat (sphinx)"
  , "Essence (sphinx)"
  , "Eye (sphinx)"
  , "Feather (sphinx)"
  , "Teeth (sphinx)"
  , "Blood (unicorn)"
  , "Scat (unicorn)"
  , "Essence (unicorn)"
  , "Eye (unicorn)"
  , "Hide (unicorn)"
  , "Teeth (unicorn)"
  , "Blood (crone)"
  , "Scat (crone)"
  , "Essence (crone)"
  , "Eye (crone)"
  , "Nail (crone)"
  , "Skin (crone)"
  , "Teeth (crone)"
  , "Blood (behemoth)"
  , "Scat (behemoth)"
  , "Essence (behemoth)"
  , "Eye (behemoth)"
  , "Nail (behemoth)"
  , "Skin (behemoth)"
  , "Teeth (behemoth)"
  , "Rune of Time Acceleration"
  , "Rune of Pouch Extension"
  , "Rune of Time Dilation"
  , "Rune of Sobriety"
  , "Rune of Gem Assembly"
  , "Rune of Friend Summoning"
  , "Tin cans connected to wire"
  , "Rune of Speedwalking"
  , "Rune of Levitation"
  , "Rune of Eternal Breath"
  ];

  function viewTrait(uint256 _id) external override view returns (string memory) {
    return pockets[_id];
  }

  function totalTraits() external override view returns (uint256) {
    return pockets.length;
  }
}

